cotx-http:
  host: 0.0.0.0
  port: 7008

mysql:
  dbHost : mm3306.mysql.radacat.com
  dbPort : 3306
  dbName : cotx
  dbUser : root
  dbPassword : Radacat2017

redis:
  - name: persistence
    password: radacat1234
    host: rm6379.redis.radacat.com
    port: 6379
    maxIdle: 20
    maxActive: 1000
  - name: nopersistence
    password: radacat1234
    host: rm6380.redis.radacat.com
    port: 6380
    maxIdle: 20
    maxActive: 1000

etcd:
  name: uid_generator
  host: 192.168.0.121
  port: 2379

metrics:
  name: metrics
  enable: false  #1:enable; 0:disable
  host: push9091.prometheus.cotxnetworks.com
  port: 9091
  interval: 6
  enable: true #1:enable; 0:disable
