// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

/**
 * Protobuf type {@code setting.DeleteVersionRequest}
 */
public final class DeleteVersionRequest extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:setting.DeleteVersionRequest)
		DeleteVersionRequestOrBuilder {
	// Use DeleteVersionRequest.newBuilder() to construct.
	private DeleteVersionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private DeleteVersionRequest() {
		id_ = 0;
		tid_ = 0L;
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	@SuppressWarnings("unused")
	private DeleteVersionRequest(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 8: {

					id_ = input.readInt32();
					break;
				}
				case 16: {

					tid_ = input.readInt64();
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_DeleteVersionRequest_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_DeleteVersionRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.DeleteVersionRequest.class,
						com.lanlian.rpc.version.DeleteVersionRequest.Builder.class);
	}

	public static final int ID_FIELD_NUMBER = 1;
	private int id_;

	/**
	 * <code>optional int32 id = 1;</code>
	 */
	public int getId() {
		return id_;
	}

	public static final int TID_FIELD_NUMBER = 2;
	private long tid_;

	/**
	 * <code>optional int64 tid = 2;</code>
	 */
	public long getTid() {
		return tid_;
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (id_ != 0) {
			output.writeInt32(1, id_);
		}
		if (tid_ != 0L) {
			output.writeInt64(2, tid_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (id_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
		}
		if (tid_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, tid_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.version.DeleteVersionRequest prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code setting.DeleteVersionRequest}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:setting.DeleteVersionRequest)
			com.lanlian.rpc.version.DeleteVersionRequestOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_DeleteVersionRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_DeleteVersionRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.DeleteVersionRequest.class,
							com.lanlian.rpc.version.DeleteVersionRequest.Builder.class);
		}

		// Construct using com.lanlian.rpc.version.DeleteVersionRequest.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			id_ = 0;

			tid_ = 0L;

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_DeleteVersionRequest_descriptor;
		}

		public com.lanlian.rpc.version.DeleteVersionRequest getDefaultInstanceForType() {
			return com.lanlian.rpc.version.DeleteVersionRequest.getDefaultInstance();
		}

		public com.lanlian.rpc.version.DeleteVersionRequest build() {
			com.lanlian.rpc.version.DeleteVersionRequest result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public com.lanlian.rpc.version.DeleteVersionRequest buildPartial() {
			com.lanlian.rpc.version.DeleteVersionRequest result = new com.lanlian.rpc.version.DeleteVersionRequest(
					this);
			result.id_ = id_;
			result.tid_ = tid_;
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.version.DeleteVersionRequest) {
				return mergeFrom((com.lanlian.rpc.version.DeleteVersionRequest) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.version.DeleteVersionRequest other) {
			if (other == com.lanlian.rpc.version.DeleteVersionRequest.getDefaultInstance())
				return this;
			if (other.getId() != 0) {
				setId(other.getId());
			}
			if (other.getTid() != 0L) {
				setTid(other.getTid());
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.version.DeleteVersionRequest parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.version.DeleteVersionRequest) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int id_;

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		public int getId() {
			return id_;
		}

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		public Builder setId(int value) {

			id_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		public Builder clearId() {

			id_ = 0;
			onChanged();
			return this;
		}

		private long tid_;

		/**
		 * <code>optional int64 tid = 2;</code>
		 */
		public long getTid() {
			return tid_;
		}

		/**
		 * <code>optional int64 tid = 2;</code>
		 */
		public Builder setTid(long value) {

			tid_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int64 tid = 2;</code>
		 */
		public Builder clearTid() {

			tid_ = 0L;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:setting.DeleteVersionRequest)
	}

	// @@protoc_insertion_point(class_scope:setting.DeleteVersionRequest)
	private static final com.lanlian.rpc.version.DeleteVersionRequest DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.version.DeleteVersionRequest();
	}

	public static com.lanlian.rpc.version.DeleteVersionRequest getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<DeleteVersionRequest> PARSER = new com.google.protobuf.AbstractParser<DeleteVersionRequest>() {
		public DeleteVersionRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new DeleteVersionRequest(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<DeleteVersionRequest> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<DeleteVersionRequest> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.version.DeleteVersionRequest getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
