// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

/**
 * Protobuf type {@code setting.GetAllVersionsRequest}
 */
public final class GetAllVersionsRequest extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:setting.GetAllVersionsRequest)
		GetAllVersionsRequestOrBuilder {
	// Use GetAllVersionsRequest.newBuilder() to construct.
	private GetAllVersionsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private GetAllVersionsRequest() {
		count_ = 0;
		page_ = 0;
		tid_ = 0L;
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	@SuppressWarnings("unused")
	private GetAllVersionsRequest(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 8: {

					count_ = input.readInt32();
					break;
				}
				case 16: {

					page_ = input.readInt32();
					break;
				}
				case 24: {

					tid_ = input.readInt64();
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsRequest_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetAllVersionsRequest.class,
						com.lanlian.rpc.version.GetAllVersionsRequest.Builder.class);
	}

	public static final int COUNT_FIELD_NUMBER = 1;
	private int count_;

	/**
	 * <code>optional int32 count = 1;</code>
	 */
	public int getCount() {
		return count_;
	}

	public static final int PAGE_FIELD_NUMBER = 2;
	private int page_;

	/**
	 * <code>optional int32 page = 2;</code>
	 */
	public int getPage() {
		return page_;
	}

	public static final int TID_FIELD_NUMBER = 3;
	private long tid_;

	/**
	 * <code>optional int64 tid = 3;</code>
	 */
	public long getTid() {
		return tid_;
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (count_ != 0) {
			output.writeInt32(1, count_);
		}
		if (page_ != 0) {
			output.writeInt32(2, page_);
		}
		if (tid_ != 0L) {
			output.writeInt64(3, tid_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (count_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, count_);
		}
		if (page_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, page_);
		}
		if (tid_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, tid_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.version.GetAllVersionsRequest prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code setting.GetAllVersionsRequest}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:setting.GetAllVersionsRequest)
			com.lanlian.rpc.version.GetAllVersionsRequestOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetAllVersionsRequest.class,
							com.lanlian.rpc.version.GetAllVersionsRequest.Builder.class);
		}

		// Construct using com.lanlian.rpc.version.GetAllVersionsRequest.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			count_ = 0;

			page_ = 0;

			tid_ = 0L;

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsRequest_descriptor;
		}

		public com.lanlian.rpc.version.GetAllVersionsRequest getDefaultInstanceForType() {
			return com.lanlian.rpc.version.GetAllVersionsRequest.getDefaultInstance();
		}

		public com.lanlian.rpc.version.GetAllVersionsRequest build() {
			com.lanlian.rpc.version.GetAllVersionsRequest result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public com.lanlian.rpc.version.GetAllVersionsRequest buildPartial() {
			com.lanlian.rpc.version.GetAllVersionsRequest result = new com.lanlian.rpc.version.GetAllVersionsRequest(
					this);
			result.count_ = count_;
			result.page_ = page_;
			result.tid_ = tid_;
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.version.GetAllVersionsRequest) {
				return mergeFrom((com.lanlian.rpc.version.GetAllVersionsRequest) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.version.GetAllVersionsRequest other) {
			if (other == com.lanlian.rpc.version.GetAllVersionsRequest.getDefaultInstance())
				return this;
			if (other.getCount() != 0) {
				setCount(other.getCount());
			}
			if (other.getPage() != 0) {
				setPage(other.getPage());
			}
			if (other.getTid() != 0L) {
				setTid(other.getTid());
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.version.GetAllVersionsRequest parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.version.GetAllVersionsRequest) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int count_;

		/**
		 * <code>optional int32 count = 1;</code>
		 */
		public int getCount() {
			return count_;
		}

		/**
		 * <code>optional int32 count = 1;</code>
		 */
		public Builder setCount(int value) {

			count_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 count = 1;</code>
		 */
		public Builder clearCount() {

			count_ = 0;
			onChanged();
			return this;
		}

		private int page_;

		/**
		 * <code>optional int32 page = 2;</code>
		 */
		public int getPage() {
			return page_;
		}

		/**
		 * <code>optional int32 page = 2;</code>
		 */
		public Builder setPage(int value) {

			page_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 page = 2;</code>
		 */
		public Builder clearPage() {

			page_ = 0;
			onChanged();
			return this;
		}

		private long tid_;

		/**
		 * <code>optional int64 tid = 3;</code>
		 */
		public long getTid() {
			return tid_;
		}

		/**
		 * <code>optional int64 tid = 3;</code>
		 */
		public Builder setTid(long value) {

			tid_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int64 tid = 3;</code>
		 */
		public Builder clearTid() {

			tid_ = 0L;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:setting.GetAllVersionsRequest)
	}

	// @@protoc_insertion_point(class_scope:setting.GetAllVersionsRequest)
	private static final com.lanlian.rpc.version.GetAllVersionsRequest DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.version.GetAllVersionsRequest();
	}

	public static com.lanlian.rpc.version.GetAllVersionsRequest getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<GetAllVersionsRequest> PARSER = new com.google.protobuf.AbstractParser<GetAllVersionsRequest>() {
		public GetAllVersionsRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new GetAllVersionsRequest(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<GetAllVersionsRequest> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<GetAllVersionsRequest> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.version.GetAllVersionsRequest getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
