// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

public interface VersionOrBuilder extends
		// @@protoc_insertion_point(interface_extends:setting.Version)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>optional string device = 1;</code>
	 */
	java.lang.String getDevice();

	/**
	 * <code>optional string device = 1;</code>
	 */
	com.google.protobuf.ByteString getDeviceBytes();

	/**
	 * <code>optional string versionName = 2;</code>
	 */
	java.lang.String getVersionName();

	/**
	 * <code>optional string versionName = 2;</code>
	 */
	com.google.protobuf.ByteString getVersionNameBytes();

	/**
	 * <code>optional string versionCode = 3;</code>
	 */
	java.lang.String getVersionCode();

	/**
	 * <code>optional string versionCode = 3;</code>
	 */
	com.google.protobuf.ByteString getVersionCodeBytes();

	/**
	 * <code>optional string md5 = 4;</code>
	 */
	java.lang.String getMd5();

	/**
	 * <code>optional string md5 = 4;</code>
	 */
	com.google.protobuf.ByteString getMd5Bytes();

	/**
	 * <code>optional string fileName = 5;</code>
	 */
	java.lang.String getFileName();

	/**
	 * <code>optional string fileName = 5;</code>
	 */
	com.google.protobuf.ByteString getFileNameBytes();

	/**
	 * <code>optional int64 length = 6;</code>
	 */
	long getLength();

	/**
	 * <code>optional string path = 7;</code>
	 */
	java.lang.String getPath();

	/**
	 * <code>optional string path = 7;</code>
	 */
	com.google.protobuf.ByteString getPathBytes();

	/**
	 * <code>optional string descriptionCn = 8;</code>
	 */
	java.lang.String getDescriptionCn();

	/**
	 * <code>optional string descriptionCn = 8;</code>
	 */
	com.google.protobuf.ByteString getDescriptionCnBytes();

	/**
	 * <code>optional string descriptionEn = 9;</code>
	 */
	java.lang.String getDescriptionEn();

	/**
	 * <code>optional string descriptionEn = 9;</code>
	 */
	com.google.protobuf.ByteString getDescriptionEnBytes();

	/**
	 * <code>optional int64 uploaderUid = 10;</code>
	 */
	long getUploaderUid();

	/**
	 * <code>optional int32 status = 11;</code>
	 */
	int getStatus();

	/**
	 * <code>optional int32 id = 12;</code>
	 */
	int getId();

	/**
	 * <code>optional int64 createTime = 13;</code>
	 */
	long getCreateTime();

	/**
	 * <code>optional int64 updateTime = 14;</code>
	 */
	long getUpdateTime();

	/**
	 * <code>optional int64 tid = 15;</code>
	 */
	long getTid();
}
