redis:
  - name: persistence
    password: radacat1234
    host: rm6379.redis.radacat.com
    port: 6379
    maxIdle: 20
    maxActive: 100
  - name: nopersistence
    password: radacat1234
    host: rm6380.redis.radacat.com
    port: 6380
    maxIdle: 20
    maxActive: 100

mysql:
  host: mm3306.mysql.radacat.com
  port: 3306
  name: file-server
  user: root
  password: Radacat2017
  maxIdle: 10
  maxOpen: 20

metrics:
  host: push9091.prometheus.radacat.com
  port: 9091
  interval: 30
  enable: true

