// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/tenant.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TenantInfo struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	TenantName           string   `protobuf:"bytes,2,opt,name=TenantName,proto3" json:"TenantName,omitempty"`
	TenantURL            string   `protobuf:"bytes,3,opt,name=TenantURL,proto3" json:"TenantURL,omitempty"`
	TenantState          int32    `protobuf:"varint,4,opt,name=TenantState,proto3" json:"TenantState,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Contacts             string   `protobuf:"bytes,6,opt,name=Contacts,proto3" json:"Contacts,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=Phone,proto3" json:"Phone,omitempty"`
	State                int32    `protobuf:"varint,9,opt,name=State,proto3" json:"State,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Icon                 string   `protobuf:"bytes,11,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Logo                 string   `protobuf:"bytes,12,opt,name=Logo,proto3" json:"Logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantInfo) Reset()         { *m = TenantInfo{} }
func (m *TenantInfo) String() string { return proto.CompactTextString(m) }
func (*TenantInfo) ProtoMessage()    {}
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{0}
}
func (m *TenantInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantInfo.Unmarshal(m, b)
}
func (m *TenantInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantInfo.Marshal(b, m, deterministic)
}
func (dst *TenantInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantInfo.Merge(dst, src)
}
func (m *TenantInfo) XXX_Size() int {
	return xxx_messageInfo_TenantInfo.Size(m)
}
func (m *TenantInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TenantInfo proto.InternalMessageInfo

func (m *TenantInfo) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *TenantInfo) GetTenantName() string {
	if m != nil {
		return m.TenantName
	}
	return ""
}

func (m *TenantInfo) GetTenantURL() string {
	if m != nil {
		return m.TenantURL
	}
	return ""
}

func (m *TenantInfo) GetTenantState() int32 {
	if m != nil {
		return m.TenantState
	}
	return 0
}

func (m *TenantInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TenantInfo) GetContacts() string {
	if m != nil {
		return m.Contacts
	}
	return ""
}

func (m *TenantInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TenantInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *TenantInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *TenantInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TenantInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *TenantInfo) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type UserRoles struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Roles                []*Role  `protobuf:"bytes,2,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRoles) Reset()         { *m = UserRoles{} }
func (m *UserRoles) String() string { return proto.CompactTextString(m) }
func (*UserRoles) ProtoMessage()    {}
func (*UserRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{1}
}
func (m *UserRoles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoles.Unmarshal(m, b)
}
func (m *UserRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoles.Marshal(b, m, deterministic)
}
func (dst *UserRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoles.Merge(dst, src)
}
func (m *UserRoles) XXX_Size() int {
	return xxx_messageInfo_UserRoles.Size(m)
}
func (m *UserRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoles.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoles proto.InternalMessageInfo

func (m *UserRoles) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRoles) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// 添加租户
type AddTenantRequest struct {
	TenantName           string   `protobuf:"bytes,1,opt,name=tenantName,proto3" json:"tenantName,omitempty"`
	TenantURL            string   `protobuf:"bytes,3,opt,name=TenantURL,proto3" json:"TenantURL,omitempty"`
	TenantState          int32    `protobuf:"varint,4,opt,name=TenantState,proto3" json:"TenantState,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Pid                  int32    `protobuf:"varint,6,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Did                  int32    `protobuf:"varint,7,opt,name=Did,proto3" json:"Did,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Contacts             string   `protobuf:"bytes,10,opt,name=Contacts,proto3" json:"Contacts,omitempty"`
	Icon                 string   `protobuf:"bytes,11,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Logo                 string   `protobuf:"bytes,12,opt,name=Logo,proto3" json:"Logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTenantRequest) Reset()         { *m = AddTenantRequest{} }
func (m *AddTenantRequest) String() string { return proto.CompactTextString(m) }
func (*AddTenantRequest) ProtoMessage()    {}
func (*AddTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{2}
}
func (m *AddTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTenantRequest.Unmarshal(m, b)
}
func (m *AddTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTenantRequest.Marshal(b, m, deterministic)
}
func (dst *AddTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTenantRequest.Merge(dst, src)
}
func (m *AddTenantRequest) XXX_Size() int {
	return xxx_messageInfo_AddTenantRequest.Size(m)
}
func (m *AddTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTenantRequest proto.InternalMessageInfo

func (m *AddTenantRequest) GetTenantName() string {
	if m != nil {
		return m.TenantName
	}
	return ""
}

func (m *AddTenantRequest) GetTenantURL() string {
	if m != nil {
		return m.TenantURL
	}
	return ""
}

func (m *AddTenantRequest) GetTenantState() int32 {
	if m != nil {
		return m.TenantState
	}
	return 0
}

func (m *AddTenantRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddTenantRequest) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AddTenantRequest) GetDid() int32 {
	if m != nil {
		return m.Did
	}
	return 0
}

func (m *AddTenantRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddTenantRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AddTenantRequest) GetContacts() string {
	if m != nil {
		return m.Contacts
	}
	return ""
}

func (m *AddTenantRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *AddTenantRequest) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type AddTenantResponse struct {
	TenantInfo           *TenantInfo `protobuf:"bytes,1,opt,name=TenantInfo,proto3" json:"TenantInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddTenantResponse) Reset()         { *m = AddTenantResponse{} }
func (m *AddTenantResponse) String() string { return proto.CompactTextString(m) }
func (*AddTenantResponse) ProtoMessage()    {}
func (*AddTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{3}
}
func (m *AddTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTenantResponse.Unmarshal(m, b)
}
func (m *AddTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTenantResponse.Marshal(b, m, deterministic)
}
func (dst *AddTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTenantResponse.Merge(dst, src)
}
func (m *AddTenantResponse) XXX_Size() int {
	return xxx_messageInfo_AddTenantResponse.Size(m)
}
func (m *AddTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTenantResponse proto.InternalMessageInfo

func (m *AddTenantResponse) GetTenantInfo() *TenantInfo {
	if m != nil {
		return m.TenantInfo
	}
	return nil
}

// 修改租户信息
type UpdateTenantRequest struct {
	TenantInfo           *TenantInfo `protobuf:"bytes,1,opt,name=TenantInfo,proto3" json:"TenantInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateTenantRequest) Reset()         { *m = UpdateTenantRequest{} }
func (m *UpdateTenantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTenantRequest) ProtoMessage()    {}
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{4}
}
func (m *UpdateTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTenantRequest.Unmarshal(m, b)
}
func (m *UpdateTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTenantRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantRequest.Merge(dst, src)
}
func (m *UpdateTenantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTenantRequest.Size(m)
}
func (m *UpdateTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantRequest proto.InternalMessageInfo

func (m *UpdateTenantRequest) GetTenantInfo() *TenantInfo {
	if m != nil {
		return m.TenantInfo
	}
	return nil
}

type UpdateTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTenantResponse) Reset()         { *m = UpdateTenantResponse{} }
func (m *UpdateTenantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTenantResponse) ProtoMessage()    {}
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{5}
}
func (m *UpdateTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTenantResponse.Unmarshal(m, b)
}
func (m *UpdateTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTenantResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantResponse.Merge(dst, src)
}
func (m *UpdateTenantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTenantResponse.Size(m)
}
func (m *UpdateTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantResponse proto.InternalMessageInfo

// 修改租户状态
type UpdateTenantStateRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTenantStateRequest) Reset()         { *m = UpdateTenantStateRequest{} }
func (m *UpdateTenantStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTenantStateRequest) ProtoMessage()    {}
func (*UpdateTenantStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{6}
}
func (m *UpdateTenantStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTenantStateRequest.Unmarshal(m, b)
}
func (m *UpdateTenantStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTenantStateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTenantStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantStateRequest.Merge(dst, src)
}
func (m *UpdateTenantStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTenantStateRequest.Size(m)
}
func (m *UpdateTenantStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantStateRequest proto.InternalMessageInfo

func (m *UpdateTenantStateRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *UpdateTenantStateRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type UpdateTenantStateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTenantStateResponse) Reset()         { *m = UpdateTenantStateResponse{} }
func (m *UpdateTenantStateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTenantStateResponse) ProtoMessage()    {}
func (*UpdateTenantStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{7}
}
func (m *UpdateTenantStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTenantStateResponse.Unmarshal(m, b)
}
func (m *UpdateTenantStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTenantStateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateTenantStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTenantStateResponse.Merge(dst, src)
}
func (m *UpdateTenantStateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTenantStateResponse.Size(m)
}
func (m *UpdateTenantStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTenantStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTenantStateResponse proto.InternalMessageInfo

// 获取租户信息
type GetTenantRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTenantRequest) Reset()         { *m = GetTenantRequest{} }
func (m *GetTenantRequest) String() string { return proto.CompactTextString(m) }
func (*GetTenantRequest) ProtoMessage()    {}
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{8}
}
func (m *GetTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantRequest.Unmarshal(m, b)
}
func (m *GetTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantRequest.Marshal(b, m, deterministic)
}
func (dst *GetTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantRequest.Merge(dst, src)
}
func (m *GetTenantRequest) XXX_Size() int {
	return xxx_messageInfo_GetTenantRequest.Size(m)
}
func (m *GetTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantRequest proto.InternalMessageInfo

func (m *GetTenantRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type GetTenantResponse struct {
	Tenant               *Tenant  `protobuf:"bytes,1,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTenantResponse) Reset()         { *m = GetTenantResponse{} }
func (m *GetTenantResponse) String() string { return proto.CompactTextString(m) }
func (*GetTenantResponse) ProtoMessage()    {}
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{9}
}
func (m *GetTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantResponse.Unmarshal(m, b)
}
func (m *GetTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantResponse.Marshal(b, m, deterministic)
}
func (dst *GetTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantResponse.Merge(dst, src)
}
func (m *GetTenantResponse) XXX_Size() int {
	return xxx_messageInfo_GetTenantResponse.Size(m)
}
func (m *GetTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantResponse proto.InternalMessageInfo

func (m *GetTenantResponse) GetTenant() *Tenant {
	if m != nil {
		return m.Tenant
	}
	return nil
}

// 获取域下租户列表
type GetTenantsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTenantsRequest) Reset()         { *m = GetTenantsRequest{} }
func (m *GetTenantsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTenantsRequest) ProtoMessage()    {}
func (*GetTenantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{10}
}
func (m *GetTenantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantsRequest.Unmarshal(m, b)
}
func (m *GetTenantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTenantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantsRequest.Merge(dst, src)
}
func (m *GetTenantsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTenantsRequest.Size(m)
}
func (m *GetTenantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantsRequest proto.InternalMessageInfo

type GetTenantsResponse struct {
	Tenants              []*TenantInfo `protobuf:"bytes,1,rep,name=Tenants,proto3" json:"Tenants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetTenantsResponse) Reset()         { *m = GetTenantsResponse{} }
func (m *GetTenantsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTenantsResponse) ProtoMessage()    {}
func (*GetTenantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{11}
}
func (m *GetTenantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantsResponse.Unmarshal(m, b)
}
func (m *GetTenantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTenantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantsResponse.Merge(dst, src)
}
func (m *GetTenantsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTenantsResponse.Size(m)
}
func (m *GetTenantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantsResponse proto.InternalMessageInfo

func (m *GetTenantsResponse) GetTenants() []*TenantInfo {
	if m != nil {
		return m.Tenants
	}
	return nil
}

// 删除指定租户
type DeleteTenantRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTenantRequest) Reset()         { *m = DeleteTenantRequest{} }
func (m *DeleteTenantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTenantRequest) ProtoMessage()    {}
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{12}
}
func (m *DeleteTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTenantRequest.Unmarshal(m, b)
}
func (m *DeleteTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTenantRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTenantRequest.Merge(dst, src)
}
func (m *DeleteTenantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTenantRequest.Size(m)
}
func (m *DeleteTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTenantRequest proto.InternalMessageInfo

func (m *DeleteTenantRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type DeleteTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTenantResponse) Reset()         { *m = DeleteTenantResponse{} }
func (m *DeleteTenantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTenantResponse) ProtoMessage()    {}
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{13}
}
func (m *DeleteTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTenantResponse.Unmarshal(m, b)
}
func (m *DeleteTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTenantResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTenantResponse.Merge(dst, src)
}
func (m *DeleteTenantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTenantResponse.Size(m)
}
func (m *DeleteTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTenantResponse proto.InternalMessageInfo

// 获取租户中成员数量
type GetUserCountInTenantRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserCountInTenantRequest) Reset()         { *m = GetUserCountInTenantRequest{} }
func (m *GetUserCountInTenantRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserCountInTenantRequest) ProtoMessage()    {}
func (*GetUserCountInTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{14}
}
func (m *GetUserCountInTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCountInTenantRequest.Unmarshal(m, b)
}
func (m *GetUserCountInTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCountInTenantRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserCountInTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCountInTenantRequest.Merge(dst, src)
}
func (m *GetUserCountInTenantRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserCountInTenantRequest.Size(m)
}
func (m *GetUserCountInTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCountInTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCountInTenantRequest proto.InternalMessageInfo

func (m *GetUserCountInTenantRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *GetUserCountInTenantRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type GetUserCountInTenantResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserCountInTenantResponse) Reset()         { *m = GetUserCountInTenantResponse{} }
func (m *GetUserCountInTenantResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserCountInTenantResponse) ProtoMessage()    {}
func (*GetUserCountInTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{15}
}
func (m *GetUserCountInTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCountInTenantResponse.Unmarshal(m, b)
}
func (m *GetUserCountInTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCountInTenantResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserCountInTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCountInTenantResponse.Merge(dst, src)
}
func (m *GetUserCountInTenantResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserCountInTenantResponse.Size(m)
}
func (m *GetUserCountInTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCountInTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCountInTenantResponse proto.InternalMessageInfo

func (m *GetUserCountInTenantResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 获取租户中成员信息
type GetUserInfoInTenantRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoInTenantRequest) Reset()         { *m = GetUserInfoInTenantRequest{} }
func (m *GetUserInfoInTenantRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoInTenantRequest) ProtoMessage()    {}
func (*GetUserInfoInTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{16}
}
func (m *GetUserInfoInTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoInTenantRequest.Unmarshal(m, b)
}
func (m *GetUserInfoInTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoInTenantRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserInfoInTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoInTenantRequest.Merge(dst, src)
}
func (m *GetUserInfoInTenantRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoInTenantRequest.Size(m)
}
func (m *GetUserInfoInTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoInTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoInTenantRequest proto.InternalMessageInfo

func (m *GetUserInfoInTenantRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserInfoInTenantRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserInfoInTenantResponse struct {
	UserRoles            []*UserRoles `protobuf:"bytes,1,rep,name=userRoles,proto3" json:"userRoles,omitempty"`
	TotalCount           int32        `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserInfoInTenantResponse) Reset()         { *m = GetUserInfoInTenantResponse{} }
func (m *GetUserInfoInTenantResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoInTenantResponse) ProtoMessage()    {}
func (*GetUserInfoInTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{17}
}
func (m *GetUserInfoInTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoInTenantResponse.Unmarshal(m, b)
}
func (m *GetUserInfoInTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoInTenantResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserInfoInTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoInTenantResponse.Merge(dst, src)
}
func (m *GetUserInfoInTenantResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoInTenantResponse.Size(m)
}
func (m *GetUserInfoInTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoInTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoInTenantResponse proto.InternalMessageInfo

func (m *GetUserInfoInTenantResponse) GetUserRoles() []*UserRoles {
	if m != nil {
		return m.UserRoles
	}
	return nil
}

func (m *GetUserInfoInTenantResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

// 修改租户中成员角色
type UpdateUserRoleInTenantRequest struct {
	UpdateUserID         int32    `protobuf:"varint,1,opt,name=updateUserID,proto3" json:"updateUserID,omitempty"`
	UpdateUserRids       []int32  `protobuf:"varint,2,rep,packed,name=updateUserRids,proto3" json:"updateUserRids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRoleInTenantRequest) Reset()         { *m = UpdateUserRoleInTenantRequest{} }
func (m *UpdateUserRoleInTenantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRoleInTenantRequest) ProtoMessage()    {}
func (*UpdateUserRoleInTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{18}
}
func (m *UpdateUserRoleInTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRoleInTenantRequest.Unmarshal(m, b)
}
func (m *UpdateUserRoleInTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRoleInTenantRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRoleInTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRoleInTenantRequest.Merge(dst, src)
}
func (m *UpdateUserRoleInTenantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRoleInTenantRequest.Size(m)
}
func (m *UpdateUserRoleInTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRoleInTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRoleInTenantRequest proto.InternalMessageInfo

func (m *UpdateUserRoleInTenantRequest) GetUpdateUserID() int32 {
	if m != nil {
		return m.UpdateUserID
	}
	return 0
}

func (m *UpdateUserRoleInTenantRequest) GetUpdateUserRids() []int32 {
	if m != nil {
		return m.UpdateUserRids
	}
	return nil
}

type UpdateUserRoleInTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRoleInTenantResponse) Reset()         { *m = UpdateUserRoleInTenantResponse{} }
func (m *UpdateUserRoleInTenantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRoleInTenantResponse) ProtoMessage()    {}
func (*UpdateUserRoleInTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{19}
}
func (m *UpdateUserRoleInTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRoleInTenantResponse.Unmarshal(m, b)
}
func (m *UpdateUserRoleInTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRoleInTenantResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRoleInTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRoleInTenantResponse.Merge(dst, src)
}
func (m *UpdateUserRoleInTenantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRoleInTenantResponse.Size(m)
}
func (m *UpdateUserRoleInTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRoleInTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRoleInTenantResponse proto.InternalMessageInfo

// 删除指定租户中用户
type DeleteUserInTenantRequest struct {
	DeleteUserID         int32    `protobuf:"varint,2,opt,name=deleteUserID,proto3" json:"deleteUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserInTenantRequest) Reset()         { *m = DeleteUserInTenantRequest{} }
func (m *DeleteUserInTenantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserInTenantRequest) ProtoMessage()    {}
func (*DeleteUserInTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{20}
}
func (m *DeleteUserInTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserInTenantRequest.Unmarshal(m, b)
}
func (m *DeleteUserInTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserInTenantRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserInTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserInTenantRequest.Merge(dst, src)
}
func (m *DeleteUserInTenantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserInTenantRequest.Size(m)
}
func (m *DeleteUserInTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserInTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserInTenantRequest proto.InternalMessageInfo

func (m *DeleteUserInTenantRequest) GetDeleteUserID() int32 {
	if m != nil {
		return m.DeleteUserID
	}
	return 0
}

type DeleteUserInTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserInTenantResponse) Reset()         { *m = DeleteUserInTenantResponse{} }
func (m *DeleteUserInTenantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserInTenantResponse) ProtoMessage()    {}
func (*DeleteUserInTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{21}
}
func (m *DeleteUserInTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserInTenantResponse.Unmarshal(m, b)
}
func (m *DeleteUserInTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserInTenantResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUserInTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserInTenantResponse.Merge(dst, src)
}
func (m *DeleteUserInTenantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserInTenantResponse.Size(m)
}
func (m *DeleteUserInTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserInTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserInTenantResponse proto.InternalMessageInfo

// 邀请用户进入指定租户
type AddUserInTenantRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	AddUserUsername      string   `protobuf:"bytes,2,opt,name=addUserUsername,proto3" json:"addUserUsername,omitempty"`
	AddUserNickname      string   `protobuf:"bytes,3,opt,name=addUserNickname,proto3" json:"addUserNickname,omitempty"`
	AddUserRids          []int32  `protobuf:"varint,4,rep,packed,name=addUserRids,proto3" json:"addUserRids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserInTenantRequest) Reset()         { *m = AddUserInTenantRequest{} }
func (m *AddUserInTenantRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserInTenantRequest) ProtoMessage()    {}
func (*AddUserInTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{22}
}
func (m *AddUserInTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserInTenantRequest.Unmarshal(m, b)
}
func (m *AddUserInTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserInTenantRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserInTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserInTenantRequest.Merge(dst, src)
}
func (m *AddUserInTenantRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserInTenantRequest.Size(m)
}
func (m *AddUserInTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserInTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserInTenantRequest proto.InternalMessageInfo

func (m *AddUserInTenantRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *AddUserInTenantRequest) GetAddUserUsername() string {
	if m != nil {
		return m.AddUserUsername
	}
	return ""
}

func (m *AddUserInTenantRequest) GetAddUserNickname() string {
	if m != nil {
		return m.AddUserNickname
	}
	return ""
}

func (m *AddUserInTenantRequest) GetAddUserRids() []int32 {
	if m != nil {
		return m.AddUserRids
	}
	return nil
}

type AddUserInTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserInTenantResponse) Reset()         { *m = AddUserInTenantResponse{} }
func (m *AddUserInTenantResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserInTenantResponse) ProtoMessage()    {}
func (*AddUserInTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{23}
}
func (m *AddUserInTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserInTenantResponse.Unmarshal(m, b)
}
func (m *AddUserInTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserInTenantResponse.Marshal(b, m, deterministic)
}
func (dst *AddUserInTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserInTenantResponse.Merge(dst, src)
}
func (m *AddUserInTenantResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserInTenantResponse.Size(m)
}
func (m *AddUserInTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserInTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserInTenantResponse proto.InternalMessageInfo

// 同意进入租户
type EnterTenantRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterTenantRequest) Reset()         { *m = EnterTenantRequest{} }
func (m *EnterTenantRequest) String() string { return proto.CompactTextString(m) }
func (*EnterTenantRequest) ProtoMessage()    {}
func (*EnterTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{24}
}
func (m *EnterTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterTenantRequest.Unmarshal(m, b)
}
func (m *EnterTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterTenantRequest.Marshal(b, m, deterministic)
}
func (dst *EnterTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterTenantRequest.Merge(dst, src)
}
func (m *EnterTenantRequest) XXX_Size() int {
	return xxx_messageInfo_EnterTenantRequest.Size(m)
}
func (m *EnterTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterTenantRequest proto.InternalMessageInfo

func (m *EnterTenantRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EnterTenantRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *EnterTenantRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type EnterTenantResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterTenantResponse) Reset()         { *m = EnterTenantResponse{} }
func (m *EnterTenantResponse) String() string { return proto.CompactTextString(m) }
func (*EnterTenantResponse) ProtoMessage()    {}
func (*EnterTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{25}
}
func (m *EnterTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterTenantResponse.Unmarshal(m, b)
}
func (m *EnterTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterTenantResponse.Marshal(b, m, deterministic)
}
func (dst *EnterTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterTenantResponse.Merge(dst, src)
}
func (m *EnterTenantResponse) XXX_Size() int {
	return xxx_messageInfo_EnterTenantResponse.Size(m)
}
func (m *EnterTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnterTenantResponse proto.InternalMessageInfo

func (m *EnterTenantResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetTidByUrlRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTidByUrlRequest) Reset()         { *m = GetTidByUrlRequest{} }
func (m *GetTidByUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetTidByUrlRequest) ProtoMessage()    {}
func (*GetTidByUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{26}
}
func (m *GetTidByUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTidByUrlRequest.Unmarshal(m, b)
}
func (m *GetTidByUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTidByUrlRequest.Marshal(b, m, deterministic)
}
func (dst *GetTidByUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTidByUrlRequest.Merge(dst, src)
}
func (m *GetTidByUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetTidByUrlRequest.Size(m)
}
func (m *GetTidByUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTidByUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTidByUrlRequest proto.InternalMessageInfo

func (m *GetTidByUrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetTidByUrlResponse struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Icon                 string   `protobuf:"bytes,2,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=Logo,proto3" json:"Logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTidByUrlResponse) Reset()         { *m = GetTidByUrlResponse{} }
func (m *GetTidByUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetTidByUrlResponse) ProtoMessage()    {}
func (*GetTidByUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{27}
}
func (m *GetTidByUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTidByUrlResponse.Unmarshal(m, b)
}
func (m *GetTidByUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTidByUrlResponse.Marshal(b, m, deterministic)
}
func (dst *GetTidByUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTidByUrlResponse.Merge(dst, src)
}
func (m *GetTidByUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetTidByUrlResponse.Size(m)
}
func (m *GetTidByUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTidByUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTidByUrlResponse proto.InternalMessageInfo

func (m *GetTidByUrlResponse) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *GetTidByUrlResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *GetTidByUrlResponse) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type GetDidByTidRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDidByTidRequest) Reset()         { *m = GetDidByTidRequest{} }
func (m *GetDidByTidRequest) String() string { return proto.CompactTextString(m) }
func (*GetDidByTidRequest) ProtoMessage()    {}
func (*GetDidByTidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{28}
}
func (m *GetDidByTidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDidByTidRequest.Unmarshal(m, b)
}
func (m *GetDidByTidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDidByTidRequest.Marshal(b, m, deterministic)
}
func (dst *GetDidByTidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDidByTidRequest.Merge(dst, src)
}
func (m *GetDidByTidRequest) XXX_Size() int {
	return xxx_messageInfo_GetDidByTidRequest.Size(m)
}
func (m *GetDidByTidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDidByTidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDidByTidRequest proto.InternalMessageInfo

func (m *GetDidByTidRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type GetDidByTidResponse struct {
	Did                  int32    `protobuf:"varint,2,opt,name=Did,proto3" json:"Did,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDidByTidResponse) Reset()         { *m = GetDidByTidResponse{} }
func (m *GetDidByTidResponse) String() string { return proto.CompactTextString(m) }
func (*GetDidByTidResponse) ProtoMessage()    {}
func (*GetDidByTidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{29}
}
func (m *GetDidByTidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDidByTidResponse.Unmarshal(m, b)
}
func (m *GetDidByTidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDidByTidResponse.Marshal(b, m, deterministic)
}
func (dst *GetDidByTidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDidByTidResponse.Merge(dst, src)
}
func (m *GetDidByTidResponse) XXX_Size() int {
	return xxx_messageInfo_GetDidByTidResponse.Size(m)
}
func (m *GetDidByTidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDidByTidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDidByTidResponse proto.InternalMessageInfo

func (m *GetDidByTidResponse) GetDid() int32 {
	if m != nil {
		return m.Did
	}
	return 0
}

type InviteUnactivatedTenantRequest struct {
	Tid                  int32    `protobuf:"varint,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUnactivatedTenantRequest) Reset()         { *m = InviteUnactivatedTenantRequest{} }
func (m *InviteUnactivatedTenantRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUnactivatedTenantRequest) ProtoMessage()    {}
func (*InviteUnactivatedTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{30}
}
func (m *InviteUnactivatedTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUnactivatedTenantRequest.Unmarshal(m, b)
}
func (m *InviteUnactivatedTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUnactivatedTenantRequest.Marshal(b, m, deterministic)
}
func (dst *InviteUnactivatedTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUnactivatedTenantRequest.Merge(dst, src)
}
func (m *InviteUnactivatedTenantRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUnactivatedTenantRequest.Size(m)
}
func (m *InviteUnactivatedTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUnactivatedTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUnactivatedTenantRequest proto.InternalMessageInfo

func (m *InviteUnactivatedTenantRequest) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *InviteUnactivatedTenantRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type InviteUnactivatedTenantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUnactivatedTenantResponse) Reset()         { *m = InviteUnactivatedTenantResponse{} }
func (m *InviteUnactivatedTenantResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUnactivatedTenantResponse) ProtoMessage()    {}
func (*InviteUnactivatedTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tenant_8856deaa799cf360, []int{31}
}
func (m *InviteUnactivatedTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUnactivatedTenantResponse.Unmarshal(m, b)
}
func (m *InviteUnactivatedTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUnactivatedTenantResponse.Marshal(b, m, deterministic)
}
func (dst *InviteUnactivatedTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUnactivatedTenantResponse.Merge(dst, src)
}
func (m *InviteUnactivatedTenantResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUnactivatedTenantResponse.Size(m)
}
func (m *InviteUnactivatedTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUnactivatedTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUnactivatedTenantResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TenantInfo)(nil), "api.TenantInfo")
	proto.RegisterType((*UserRoles)(nil), "api.UserRoles")
	proto.RegisterType((*AddTenantRequest)(nil), "api.AddTenantRequest")
	proto.RegisterType((*AddTenantResponse)(nil), "api.AddTenantResponse")
	proto.RegisterType((*UpdateTenantRequest)(nil), "api.UpdateTenantRequest")
	proto.RegisterType((*UpdateTenantResponse)(nil), "api.UpdateTenantResponse")
	proto.RegisterType((*UpdateTenantStateRequest)(nil), "api.UpdateTenantStateRequest")
	proto.RegisterType((*UpdateTenantStateResponse)(nil), "api.UpdateTenantStateResponse")
	proto.RegisterType((*GetTenantRequest)(nil), "api.GetTenantRequest")
	proto.RegisterType((*GetTenantResponse)(nil), "api.GetTenantResponse")
	proto.RegisterType((*GetTenantsRequest)(nil), "api.GetTenantsRequest")
	proto.RegisterType((*GetTenantsResponse)(nil), "api.GetTenantsResponse")
	proto.RegisterType((*DeleteTenantRequest)(nil), "api.DeleteTenantRequest")
	proto.RegisterType((*DeleteTenantResponse)(nil), "api.DeleteTenantResponse")
	proto.RegisterType((*GetUserCountInTenantRequest)(nil), "api.GetUserCountInTenantRequest")
	proto.RegisterType((*GetUserCountInTenantResponse)(nil), "api.GetUserCountInTenantResponse")
	proto.RegisterType((*GetUserInfoInTenantRequest)(nil), "api.GetUserInfoInTenantRequest")
	proto.RegisterType((*GetUserInfoInTenantResponse)(nil), "api.GetUserInfoInTenantResponse")
	proto.RegisterType((*UpdateUserRoleInTenantRequest)(nil), "api.UpdateUserRoleInTenantRequest")
	proto.RegisterType((*UpdateUserRoleInTenantResponse)(nil), "api.UpdateUserRoleInTenantResponse")
	proto.RegisterType((*DeleteUserInTenantRequest)(nil), "api.DeleteUserInTenantRequest")
	proto.RegisterType((*DeleteUserInTenantResponse)(nil), "api.DeleteUserInTenantResponse")
	proto.RegisterType((*AddUserInTenantRequest)(nil), "api.AddUserInTenantRequest")
	proto.RegisterType((*AddUserInTenantResponse)(nil), "api.AddUserInTenantResponse")
	proto.RegisterType((*EnterTenantRequest)(nil), "api.EnterTenantRequest")
	proto.RegisterType((*EnterTenantResponse)(nil), "api.EnterTenantResponse")
	proto.RegisterType((*GetTidByUrlRequest)(nil), "api.GetTidByUrlRequest")
	proto.RegisterType((*GetTidByUrlResponse)(nil), "api.GetTidByUrlResponse")
	proto.RegisterType((*GetDidByTidRequest)(nil), "api.GetDidByTidRequest")
	proto.RegisterType((*GetDidByTidResponse)(nil), "api.GetDidByTidResponse")
	proto.RegisterType((*InviteUnactivatedTenantRequest)(nil), "api.InviteUnactivatedTenantRequest")
	proto.RegisterType((*InviteUnactivatedTenantResponse)(nil), "api.InviteUnactivatedTenantResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TenantServerClient is the client API for TenantServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TenantServerClient interface {
	AddTenant(ctx context.Context, in *AddTenantRequest, opts ...grpc.CallOption) (*AddTenantResponse, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error)
	UpdateTenantState(ctx context.Context, in *UpdateTenantStateRequest, opts ...grpc.CallOption) (*UpdateTenantStateResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	GetTenants(ctx context.Context, in *GetTenantsRequest, opts ...grpc.CallOption) (*GetTenantsResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	GetUserCountInTenant(ctx context.Context, in *GetUserCountInTenantRequest, opts ...grpc.CallOption) (*GetUserCountInTenantResponse, error)
	GetUserInfoInTenant(ctx context.Context, in *GetUserInfoInTenantRequest, opts ...grpc.CallOption) (*GetUserInfoInTenantResponse, error)
	UpdateUserRoleInTenant(ctx context.Context, in *UpdateUserRoleInTenantRequest, opts ...grpc.CallOption) (*UpdateUserRoleInTenantResponse, error)
	AddUserInTenant(ctx context.Context, in *AddUserInTenantRequest, opts ...grpc.CallOption) (*AddUserInTenantResponse, error)
	DeleteUserInTenant(ctx context.Context, in *DeleteUserInTenantRequest, opts ...grpc.CallOption) (*DeleteUserInTenantResponse, error)
	InviteUnactivatedTenant(ctx context.Context, in *InviteUnactivatedTenantRequest, opts ...grpc.CallOption) (*InviteUnactivatedTenantResponse, error)
	EnterTenant(ctx context.Context, in *EnterTenantRequest, opts ...grpc.CallOption) (*EnterTenantResponse, error)
	GetTidByUrl(ctx context.Context, in *GetTidByUrlRequest, opts ...grpc.CallOption) (*GetTidByUrlResponse, error)
	GetDidByTid(ctx context.Context, in *GetDidByTidRequest, opts ...grpc.CallOption) (*GetDidByTidResponse, error)
}

type tenantServerClient struct {
	cc *grpc.ClientConn
}

func NewTenantServerClient(cc *grpc.ClientConn) TenantServerClient {
	return &tenantServerClient{cc}
}

func (c *tenantServerClient) AddTenant(ctx context.Context, in *AddTenantRequest, opts ...grpc.CallOption) (*AddTenantResponse, error) {
	out := new(AddTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/AddTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error) {
	out := new(UpdateTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/UpdateTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) UpdateTenantState(ctx context.Context, in *UpdateTenantStateRequest, opts ...grpc.CallOption) (*UpdateTenantStateResponse, error) {
	out := new(UpdateTenantStateResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/UpdateTenantState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetTenants(ctx context.Context, in *GetTenantsRequest, opts ...grpc.CallOption) (*GetTenantsResponse, error) {
	out := new(GetTenantsResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetTenants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/DeleteTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetUserCountInTenant(ctx context.Context, in *GetUserCountInTenantRequest, opts ...grpc.CallOption) (*GetUserCountInTenantResponse, error) {
	out := new(GetUserCountInTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetUserCountInTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetUserInfoInTenant(ctx context.Context, in *GetUserInfoInTenantRequest, opts ...grpc.CallOption) (*GetUserInfoInTenantResponse, error) {
	out := new(GetUserInfoInTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetUserInfoInTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) UpdateUserRoleInTenant(ctx context.Context, in *UpdateUserRoleInTenantRequest, opts ...grpc.CallOption) (*UpdateUserRoleInTenantResponse, error) {
	out := new(UpdateUserRoleInTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/UpdateUserRoleInTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) AddUserInTenant(ctx context.Context, in *AddUserInTenantRequest, opts ...grpc.CallOption) (*AddUserInTenantResponse, error) {
	out := new(AddUserInTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/AddUserInTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) DeleteUserInTenant(ctx context.Context, in *DeleteUserInTenantRequest, opts ...grpc.CallOption) (*DeleteUserInTenantResponse, error) {
	out := new(DeleteUserInTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/DeleteUserInTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) InviteUnactivatedTenant(ctx context.Context, in *InviteUnactivatedTenantRequest, opts ...grpc.CallOption) (*InviteUnactivatedTenantResponse, error) {
	out := new(InviteUnactivatedTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/InviteUnactivatedTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) EnterTenant(ctx context.Context, in *EnterTenantRequest, opts ...grpc.CallOption) (*EnterTenantResponse, error) {
	out := new(EnterTenantResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/EnterTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetTidByUrl(ctx context.Context, in *GetTidByUrlRequest, opts ...grpc.CallOption) (*GetTidByUrlResponse, error) {
	out := new(GetTidByUrlResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetTidByUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServerClient) GetDidByTid(ctx context.Context, in *GetDidByTidRequest, opts ...grpc.CallOption) (*GetDidByTidResponse, error) {
	out := new(GetDidByTidResponse)
	err := c.cc.Invoke(ctx, "/api.TenantServer/GetDidByTid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServerServer is the server API for TenantServer service.
type TenantServerServer interface {
	AddTenant(context.Context, *AddTenantRequest) (*AddTenantResponse, error)
	UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error)
	UpdateTenantState(context.Context, *UpdateTenantStateRequest) (*UpdateTenantStateResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	GetTenants(context.Context, *GetTenantsRequest) (*GetTenantsResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	GetUserCountInTenant(context.Context, *GetUserCountInTenantRequest) (*GetUserCountInTenantResponse, error)
	GetUserInfoInTenant(context.Context, *GetUserInfoInTenantRequest) (*GetUserInfoInTenantResponse, error)
	UpdateUserRoleInTenant(context.Context, *UpdateUserRoleInTenantRequest) (*UpdateUserRoleInTenantResponse, error)
	AddUserInTenant(context.Context, *AddUserInTenantRequest) (*AddUserInTenantResponse, error)
	DeleteUserInTenant(context.Context, *DeleteUserInTenantRequest) (*DeleteUserInTenantResponse, error)
	InviteUnactivatedTenant(context.Context, *InviteUnactivatedTenantRequest) (*InviteUnactivatedTenantResponse, error)
	EnterTenant(context.Context, *EnterTenantRequest) (*EnterTenantResponse, error)
	GetTidByUrl(context.Context, *GetTidByUrlRequest) (*GetTidByUrlResponse, error)
	GetDidByTid(context.Context, *GetDidByTidRequest) (*GetDidByTidResponse, error)
}

func RegisterTenantServerServer(s *grpc.Server, srv TenantServerServer) {
	s.RegisterService(&_TenantServer_serviceDesc, srv)
}

func _TenantServer_AddTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).AddTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/AddTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).AddTenant(ctx, req.(*AddTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/UpdateTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_UpdateTenantState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).UpdateTenantState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/UpdateTenantState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).UpdateTenantState(ctx, req.(*UpdateTenantStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetTenants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetTenants(ctx, req.(*GetTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/DeleteTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetUserCountInTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCountInTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetUserCountInTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetUserCountInTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetUserCountInTenant(ctx, req.(*GetUserCountInTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetUserInfoInTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoInTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetUserInfoInTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetUserInfoInTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetUserInfoInTenant(ctx, req.(*GetUserInfoInTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_UpdateUserRoleInTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleInTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).UpdateUserRoleInTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/UpdateUserRoleInTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).UpdateUserRoleInTenant(ctx, req.(*UpdateUserRoleInTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_AddUserInTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserInTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).AddUserInTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/AddUserInTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).AddUserInTenant(ctx, req.(*AddUserInTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_DeleteUserInTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserInTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).DeleteUserInTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/DeleteUserInTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).DeleteUserInTenant(ctx, req.(*DeleteUserInTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_InviteUnactivatedTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUnactivatedTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).InviteUnactivatedTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/InviteUnactivatedTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).InviteUnactivatedTenant(ctx, req.(*InviteUnactivatedTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_EnterTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).EnterTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/EnterTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).EnterTenant(ctx, req.(*EnterTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetTidByUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTidByUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetTidByUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetTidByUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetTidByUrl(ctx, req.(*GetTidByUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantServer_GetDidByTid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDidByTidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServerServer).GetDidByTid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TenantServer/GetDidByTid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServerServer).GetDidByTid(ctx, req.(*GetDidByTidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TenantServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TenantServer",
	HandlerType: (*TenantServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTenant",
			Handler:    _TenantServer_AddTenant_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _TenantServer_UpdateTenant_Handler,
		},
		{
			MethodName: "UpdateTenantState",
			Handler:    _TenantServer_UpdateTenantState_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantServer_GetTenant_Handler,
		},
		{
			MethodName: "GetTenants",
			Handler:    _TenantServer_GetTenants_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _TenantServer_DeleteTenant_Handler,
		},
		{
			MethodName: "GetUserCountInTenant",
			Handler:    _TenantServer_GetUserCountInTenant_Handler,
		},
		{
			MethodName: "GetUserInfoInTenant",
			Handler:    _TenantServer_GetUserInfoInTenant_Handler,
		},
		{
			MethodName: "UpdateUserRoleInTenant",
			Handler:    _TenantServer_UpdateUserRoleInTenant_Handler,
		},
		{
			MethodName: "AddUserInTenant",
			Handler:    _TenantServer_AddUserInTenant_Handler,
		},
		{
			MethodName: "DeleteUserInTenant",
			Handler:    _TenantServer_DeleteUserInTenant_Handler,
		},
		{
			MethodName: "InviteUnactivatedTenant",
			Handler:    _TenantServer_InviteUnactivatedTenant_Handler,
		},
		{
			MethodName: "EnterTenant",
			Handler:    _TenantServer_EnterTenant_Handler,
		},
		{
			MethodName: "GetTidByUrl",
			Handler:    _TenantServer_GetTidByUrl_Handler,
		},
		{
			MethodName: "GetDidByTid",
			Handler:    _TenantServer_GetDidByTid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenant.proto",
}

func init() { proto.RegisterFile("api/tenant.proto", fileDescriptor_tenant_8856deaa799cf360) }

var fileDescriptor_tenant_8856deaa799cf360 = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0xb6, 0xfe, 0x1c, 0xed, 0xc8, 0xb0, 0x65, 0x4a, 0x95, 0xd7, 0x6b, 0x5b, 0x56, 0x98, 0x20,
	0x75, 0xd1, 0xc2, 0x01, 0xd2, 0x1e, 0x7a, 0x08, 0x60, 0xd8, 0x96, 0x13, 0x18, 0x0d, 0xdc, 0x60,
	0x2b, 0xa1, 0x40, 0x81, 0x1e, 0x36, 0x5a, 0x26, 0x26, 0x2c, 0xef, 0xaa, 0xbb, 0x94, 0x8b, 0xbe,
	0x4d, 0x8f, 0x3d, 0xf4, 0x39, 0xfa, 0x5c, 0x05, 0x7f, 0x96, 0xe4, 0xfe, 0xb9, 0xed, 0xa5, 0x07,
	0x01, 0xe4, 0x37, 0xb3, 0x1f, 0x87, 0x33, 0xc3, 0x6f, 0x20, 0xe8, 0x07, 0x2b, 0xfa, 0x92, 0x91,
	0x28, 0x88, 0xd8, 0xe9, 0x2a, 0x89, 0x59, 0x8c, 0x5a, 0xc1, 0x8a, 0x7a, 0xdb, 0x1c, 0x0e, 0xd6,
	0xec, 0x56, 0x82, 0xf8, 0xaf, 0x26, 0xc0, 0x4c, 0x78, 0x5d, 0x47, 0x1f, 0x63, 0xd4, 0x87, 0xd6,
	0x8c, 0x86, 0x6e, 0x63, 0xd2, 0x38, 0xe9, 0xf8, 0x7c, 0x89, 0xc6, 0x99, 0xfd, 0x26, 0xb8, 0x27,
	0x6e, 0x73, 0xd2, 0x38, 0x71, 0x7c, 0x0b, 0x41, 0x87, 0xe0, 0xc8, 0xdd, 0xdc, 0x7f, 0xe7, 0xb6,
	0x84, 0xd9, 0x00, 0x68, 0x02, 0x3d, 0xb9, 0xf9, 0x81, 0x05, 0x8c, 0xb8, 0x6d, 0xc1, 0x6b, 0x43,
	0xdc, 0x63, 0x4a, 0xd2, 0x45, 0x42, 0x57, 0x8c, 0xc6, 0x91, 0xdb, 0x11, 0x0c, 0x36, 0x84, 0x3c,
	0xe8, 0x5e, 0xc6, 0x11, 0x0b, 0x16, 0x2c, 0x75, 0x37, 0x85, 0x59, 0xef, 0xd1, 0x10, 0x3a, 0x57,
	0xf7, 0x01, 0x5d, 0xba, 0x4f, 0x84, 0x41, 0x6e, 0x38, 0xfa, 0xfe, 0x36, 0x8e, 0x88, 0xdb, 0x95,
	0xa8, 0xd8, 0x70, 0x54, 0x46, 0xe1, 0x88, 0x28, 0xe4, 0x86, 0xdf, 0xef, 0x32, 0x21, 0x01, 0x23,
	0x33, 0x7a, 0x4f, 0x5c, 0x98, 0x34, 0x4e, 0x5a, 0xbe, 0x85, 0x20, 0x04, 0xed, 0xeb, 0x45, 0x1c,
	0xb9, 0x3d, 0x41, 0x25, 0xd6, 0x1c, 0x7b, 0x17, 0x7f, 0x8a, 0xdd, 0x2d, 0x89, 0xf1, 0x35, 0xfe,
	0x0e, 0x9c, 0x79, 0x4a, 0x12, 0x3f, 0x5e, 0x92, 0x14, 0x1d, 0x41, 0x9b, 0x6f, 0x44, 0x1e, 0x7b,
	0xaf, 0x9c, 0xd3, 0x60, 0x45, 0x4f, 0x85, 0x55, 0xc0, 0xe8, 0x18, 0x3a, 0xc2, 0xcf, 0x6d, 0x4e,
	0x5a, 0xda, 0xce, 0x11, 0x5f, 0xe2, 0xf8, 0x8f, 0x26, 0xf4, 0xcf, 0xc3, 0x50, 0xe6, 0xc9, 0x27,
	0xbf, 0xac, 0x49, 0xca, 0x78, 0xa4, 0xcc, 0x54, 0xa2, 0x21, 0x2b, 0xc1, 0xfe, 0xcf, 0x4a, 0xf4,
	0xa1, 0xf5, 0x9e, 0x86, 0xa2, 0x08, 0x1d, 0x9f, 0x2f, 0x39, 0x32, 0xa5, 0xa1, 0xc8, 0x7e, 0xc7,
	0xe7, 0x4b, 0x53, 0x91, 0x6e, 0x65, 0x45, 0x1c, 0xbb, 0x22, 0x76, 0x65, 0xa1, 0x50, 0xd9, 0x7f,
	0x9b, 0xf7, 0x29, 0xec, 0x5a, 0x99, 0x4a, 0x57, 0x71, 0x94, 0x12, 0xf4, 0xd2, 0x6e, 0x6a, 0x55,
	0x85, 0x1d, 0x91, 0x65, 0x03, 0xfb, 0x96, 0x0b, 0x7e, 0x03, 0x83, 0xf9, 0x2a, 0xe4, 0x35, 0xcf,
	0xa5, 0xfc, 0x3f, 0xf3, 0x8c, 0x60, 0x98, 0xe7, 0x91, 0x01, 0xe1, 0x0b, 0x70, 0x6d, 0x5c, 0x24,
	0x3c, 0x3b, 0xa4, 0xfc, 0xe6, 0x74, 0xa7, 0x36, 0xad, 0x4e, 0xc5, 0x07, 0xb0, 0x5f, 0xc1, 0xa1,
	0x0e, 0x78, 0x0e, 0xfd, 0xb7, 0x84, 0xe5, 0xa3, 0xef, 0x43, 0x8b, 0x19, 0x62, 0x46, 0x43, 0xfc,
	0x2d, 0xec, 0x5a, 0x5e, 0x2a, 0x59, 0xcf, 0x60, 0x53, 0x22, 0xea, 0x82, 0x3d, 0xeb, 0x82, 0xbe,
	0x32, 0xe1, 0x81, 0xf5, 0x65, 0xaa, 0x0e, 0xc0, 0x67, 0x80, 0x6c, 0x50, 0xf1, 0x7d, 0x01, 0x4f,
	0x14, 0xe4, 0x36, 0x44, 0x7f, 0x97, 0x32, 0x96, 0xd9, 0xf1, 0xe7, 0x30, 0x98, 0x92, 0x25, 0x29,
	0xa6, 0xbd, 0x1c, 0xf8, 0x08, 0x86, 0x79, 0x47, 0x75, 0xed, 0x73, 0x38, 0x78, 0x4b, 0x18, 0x7f,
	0x54, 0x97, 0xf1, 0x9a, 0xb3, 0xff, 0x03, 0x11, 0x47, 0xd6, 0x34, 0x54, 0x89, 0xe5, 0x4b, 0xfc,
	0x0d, 0x1c, 0x56, 0x53, 0xa8, 0xeb, 0x0c, 0xa1, 0xb3, 0xe0, 0x06, 0xc5, 0x22, 0x37, 0xf8, 0x0d,
	0x78, 0xea, 0x2b, 0x7e, 0xa3, 0xe2, 0xb9, 0x08, 0xda, 0xab, 0xe0, 0x13, 0x51, 0x9f, 0x88, 0xb5,
	0xe1, 0x69, 0xda, 0x3c, 0x77, 0xfa, 0x02, 0x79, 0x1e, 0x75, 0xf8, 0x57, 0xe0, 0xac, 0x33, 0x55,
	0x51, 0xd9, 0xdc, 0x36, 0x6a, 0xc2, 0x51, 0xdf, 0x38, 0x08, 0x85, 0x88, 0x59, 0xb0, 0xbc, 0xb4,
	0xce, 0xb1, 0x10, 0x7c, 0x07, 0x47, 0xb2, 0x83, 0xb2, 0xaf, 0x8b, 0x71, 0x63, 0xd8, 0x5a, 0x6b,
	0x87, 0xeb, 0xa9, 0x8a, 0x3f, 0x87, 0xa1, 0x17, 0xb0, 0x6d, 0xf6, 0x3e, 0x0d, 0xa5, 0x8a, 0x75,
	0xfc, 0x02, 0x8a, 0x27, 0x30, 0xae, 0x3b, 0x4c, 0x15, 0xef, 0x0c, 0xf6, 0x65, 0x51, 0xe5, 0xf5,
	0x4b, 0xa1, 0x84, 0xc6, 0x38, 0x55, 0xb7, 0xc9, 0x61, 0xf8, 0x10, 0xbc, 0x2a, 0x02, 0x45, 0xff,
	0x7b, 0x03, 0x46, 0xe7, 0x61, 0x58, 0x45, 0x5e, 0xee, 0x8b, 0x13, 0xd8, 0x09, 0xa4, 0x2f, 0xff,
	0x45, 0x66, 0xd6, 0x15, 0x61, 0xcb, 0xf3, 0x86, 0x2e, 0xee, 0x84, 0x67, 0x2b, 0xe7, 0x99, 0xc1,
	0x5c, 0x50, 0x15, 0x24, 0xd2, 0xd4, 0x16, 0x69, 0xb2, 0x21, 0xbc, 0x0f, 0x7b, 0xa5, 0x08, 0x55,
	0xf4, 0x1f, 0x00, 0x5d, 0x45, 0x8c, 0x24, 0xf9, 0xc0, 0x3d, 0xe8, 0xae, 0x82, 0x34, 0xfd, 0x35,
	0x4e, 0x42, 0x35, 0x01, 0xf4, 0x9e, 0xdb, 0xa2, 0x2c, 0x22, 0x19, 0xbb, 0xde, 0xf3, 0xe6, 0x63,
	0xf1, 0x1d, 0x89, 0x54, 0xa8, 0x72, 0x83, 0xbf, 0x84, 0x41, 0xee, 0x0c, 0xd3, 0xf1, 0xd2, 0xb9,
	0x61, 0x3b, 0xbf, 0x90, 0x8f, 0x9d, 0x86, 0x17, 0xbf, 0xcd, 0x93, 0xa5, 0x95, 0xc9, 0x79, 0xb2,
	0x54, 0x9e, 0x7c, 0x89, 0xbf, 0x87, 0x41, 0xce, 0x4f, 0x91, 0x96, 0x55, 0x2e, 0x53, 0xf8, 0x66,
	0x85, 0xc2, 0xb7, 0x2c, 0x85, 0x97, 0x07, 0x4f, 0x39, 0xe1, 0x8c, 0x86, 0xb5, 0xaa, 0xc9, 0xc5,
	0x24, 0xe7, 0x67, 0x0e, 0x9e, 0x9a, 0x17, 0x3f, 0xa5, 0x21, 0xbe, 0x81, 0xf1, 0x75, 0xf4, 0x40,
	0x19, 0x99, 0x47, 0xc1, 0x82, 0xd1, 0x87, 0x80, 0x91, 0xb0, 0xd4, 0x1f, 0x85, 0x60, 0x3d, 0xe8,
	0x16, 0x1a, 0x43, 0xef, 0xf1, 0x53, 0x38, 0xae, 0xe5, 0x93, 0x41, 0xbc, 0xfa, 0xd3, 0x81, 0x2d,
	0x25, 0xdb, 0x24, 0x79, 0x20, 0x09, 0x7a, 0x0d, 0x8e, 0x1e, 0x5b, 0xe8, 0x33, 0xf1, 0xa4, 0x8b,
	0x03, 0xdf, 0x1b, 0x15, 0x61, 0xd5, 0x1a, 0x1b, 0xe8, 0x0a, 0xb6, 0xec, 0x51, 0x80, 0x5c, 0xa9,
	0x09, 0xe5, 0x09, 0xe6, 0xed, 0x57, 0x58, 0x34, 0xcd, 0x0c, 0x76, 0x4b, 0x13, 0x05, 0x1d, 0x95,
	0xbe, 0xb0, 0xa7, 0x95, 0x37, 0xae, 0x33, 0x6b, 0xd6, 0xd7, 0xe0, 0xe8, 0xa9, 0xa0, 0xae, 0x56,
	0x1c, 0x4d, 0xea, 0x6a, 0xa5, 0x59, 0x84, 0x37, 0xd0, 0x19, 0x80, 0x99, 0x29, 0xa8, 0xe0, 0x97,
	0x4d, 0x1e, 0x6f, 0xaf, 0x84, 0xdb, 0xb9, 0xb1, 0x47, 0x85, 0xca, 0x4d, 0xc5, 0x98, 0x51, 0xb9,
	0xa9, 0x9c, 0x2b, 0x1b, 0xe8, 0x67, 0x18, 0x56, 0x8d, 0x05, 0x34, 0xc9, 0x4e, 0xae, 0x1b, 0x3a,
	0xde, 0xd3, 0x47, 0x3c, 0x34, 0xfd, 0x4f, 0xa2, 0x59, 0x8b, 0xba, 0x8f, 0x8e, 0xed, 0x6f, 0x2b,
	0x26, 0x8b, 0x37, 0xa9, 0x77, 0xd0, 0xdc, 0x0b, 0x18, 0x55, 0x2b, 0x2f, 0xc2, 0x56, 0xf1, 0x6a,
	0x66, 0x80, 0xf7, 0xec, 0x51, 0x1f, 0x7d, 0xc8, 0x0d, 0xec, 0x14, 0xa4, 0x0b, 0x1d, 0x64, 0xfd,
	0x5a, 0x21, 0xb9, 0xde, 0x61, 0xb5, 0x51, 0xf3, 0xfd, 0x08, 0xa8, 0xac, 0xe5, 0x68, 0x6c, 0x95,
	0xa8, 0x8a, 0xf5, 0xb8, 0xd6, 0xae, 0x89, 0x3f, 0xc2, 0x5e, 0xcd, 0xeb, 0x44, 0xf2, 0xaa, 0x8f,
	0x6b, 0x81, 0xf7, 0xfc, 0x71, 0x27, 0x7d, 0xce, 0x05, 0xf4, 0x2c, 0x31, 0x45, 0xb2, 0x43, 0xcb,
	0x12, 0xee, 0xb9, 0x65, 0x83, 0xcd, 0x61, 0x69, 0x27, 0x32, 0x5d, 0x9e, 0x57, 0x5d, 0xc5, 0x51,
	0x21, 0xb3, 0x9a, 0x23, 0x93, 0x41, 0xc3, 0x51, 0x10, 0x50, 0xc3, 0x51, 0x54, 0x4c, 0xbc, 0xf1,
	0x61, 0x53, 0xfc, 0x39, 0xfc, 0xfa, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x1a, 0x4d, 0x20,
	0x45, 0x0e, 0x00, 0x00,
}
