// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twins-agent.proto

package com.lanlian.rpc.twins;

public interface AddTwinsAgentResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:api.AddTwinsAgentResponse)
		com.google.protobuf.MessageOrBuilder {
}
