// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/setting/radacat_version.proto

/*
Package setting is a generated protocol buffer package.

It is generated from these files:
	pb/setting/radacat_version.proto

It has these top-level messages:
	Version
	GetLatestVersionRequest
	GetLatestVersionResponse
*/
package setting

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	Device        string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	VersionName   string `protobuf:"bytes,2,opt,name=versionName" json:"versionName,omitempty"`
	VersionCode   string `protobuf:"bytes,3,opt,name=versionCode" json:"versionCode,omitempty"`
	Md5           string `protobuf:"bytes,4,opt,name=md5" json:"md5,omitempty"`
	FileName      string `protobuf:"bytes,5,opt,name=fileName" json:"fileName,omitempty"`
	Length        int64  `protobuf:"varint,6,opt,name=length" json:"length,omitempty"`
	Path          string `protobuf:"bytes,7,opt,name=path" json:"path,omitempty"`
	DescriptionCn string `protobuf:"bytes,8,opt,name=descriptionCn" json:"descriptionCn,omitempty"`
	DescriptionEn string `protobuf:"bytes,9,opt,name=descriptionEn" json:"descriptionEn,omitempty"`
	UploaderUid   int64  `protobuf:"varint,10,opt,name=uploaderUid" json:"uploaderUid,omitempty"`
	Status        int32  `protobuf:"varint,11,opt,name=status" json:"status,omitempty"`
	Id            int32  `protobuf:"varint,12,opt,name=id" json:"id,omitempty"`
	CreateTime    int64  `protobuf:"varint,13,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime    int64  `protobuf:"varint,14,opt,name=updateTime" json:"updateTime,omitempty"`
	Tid           int64  `protobuf:"varint,15,opt,name=tid" json:"tid,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Version) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *Version) GetVersionCode() string {
	if m != nil {
		return m.VersionCode
	}
	return ""
}

func (m *Version) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *Version) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Version) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Version) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Version) GetDescriptionCn() string {
	if m != nil {
		return m.DescriptionCn
	}
	return ""
}

func (m *Version) GetDescriptionEn() string {
	if m != nil {
		return m.DescriptionEn
	}
	return ""
}

func (m *Version) GetUploaderUid() int64 {
	if m != nil {
		return m.UploaderUid
	}
	return 0
}

func (m *Version) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Version) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Version) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Version) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Version) GetTid() int64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

type GetLatestVersionRequest struct {
	Device   string `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
}

func (m *GetLatestVersionRequest) Reset()                    { *m = GetLatestVersionRequest{} }
func (m *GetLatestVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLatestVersionRequest) ProtoMessage()               {}
func (*GetLatestVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetLatestVersionRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *GetLatestVersionRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetLatestVersionRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetLatestVersionResponse struct {
	ErrorCode int32    `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"`
	Version   *Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetLatestVersionResponse) Reset()                    { *m = GetLatestVersionResponse{} }
func (m *GetLatestVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLatestVersionResponse) ProtoMessage()               {}
func (*GetLatestVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetLatestVersionResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetLatestVersionResponse) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func init() {
	proto.RegisterType((*Version)(nil), "setting.Version")
	proto.RegisterType((*GetLatestVersionRequest)(nil), "setting.GetLatestVersionRequest")
	proto.RegisterType((*GetLatestVersionResponse)(nil), "setting.GetLatestVersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RadacatVersion service

type RadacatVersionClient interface {
	GetLatestVersion(ctx context.Context, in *GetLatestVersionRequest, opts ...grpc.CallOption) (*GetLatestVersionResponse, error)
}

type radacatVersionClient struct {
	cc *grpc.ClientConn
}

func NewRadacatVersionClient(cc *grpc.ClientConn) RadacatVersionClient {
	return &radacatVersionClient{cc}
}

func (c *radacatVersionClient) GetLatestVersion(ctx context.Context, in *GetLatestVersionRequest, opts ...grpc.CallOption) (*GetLatestVersionResponse, error) {
	out := new(GetLatestVersionResponse)
	err := grpc.Invoke(ctx, "/setting.RadacatVersion/GetLatestVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RadacatVersion service

type RadacatVersionServer interface {
	GetLatestVersion(context.Context, *GetLatestVersionRequest) (*GetLatestVersionResponse, error)
}

func RegisterRadacatVersionServer(s *grpc.Server, srv RadacatVersionServer) {
	s.RegisterService(&_RadacatVersion_serviceDesc, srv)
}

func _RadacatVersion_GetLatestVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RadacatVersionServer).GetLatestVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/setting.RadacatVersion/GetLatestVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RadacatVersionServer).GetLatestVersion(ctx, req.(*GetLatestVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RadacatVersion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "setting.RadacatVersion",
	HandlerType: (*RadacatVersionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestVersion",
			Handler:    _RadacatVersion_GetLatestVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/setting/radacat_version.proto",
}

func init() { proto.RegisterFile("pb/setting/radacat_version.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x8e, 0xda, 0x30,
	0x10, 0x6e, 0x08, 0x10, 0x18, 0x0a, 0x45, 0x3e, 0xb4, 0x16, 0xaa, 0xaa, 0x34, 0xea, 0x01, 0xf5,
	0x00, 0x12, 0x55, 0x9f, 0xa0, 0x42, 0xbd, 0x54, 0x3d, 0x44, 0x6d, 0xa5, 0x9e, 0x2a, 0x13, 0x4f,
	0xc1, 0x5a, 0xb0, 0xb3, 0xb6, 0xc3, 0x2b, 0xed, 0x6b, 0xae, 0xec, 0x38, 0x10, 0x40, 0xec, 0xcd,
	0xdf, 0x8f, 0x67, 0xc6, 0xfe, 0x06, 0xd2, 0x72, 0xb3, 0x34, 0x68, 0xad, 0x90, 0xdb, 0xa5, 0x66,
	0x9c, 0x15, 0xcc, 0xfe, 0x3b, 0xa2, 0x36, 0x42, 0xc9, 0x45, 0xa9, 0x95, 0x55, 0x24, 0x09, 0x72,
	0xf6, 0x14, 0x43, 0xf2, 0xa7, 0x96, 0xc8, 0x5b, 0xe8, 0x73, 0x3c, 0x8a, 0x02, 0x69, 0x94, 0x46,
	0xf3, 0x61, 0x1e, 0x10, 0x49, 0x61, 0x14, 0x6e, 0xff, 0x64, 0x07, 0xa4, 0x1d, 0x2f, 0xb6, 0xa9,
	0x96, 0xe3, 0x9b, 0xe2, 0x48, 0xe3, 0x0b, 0x87, 0xa3, 0xc8, 0x14, 0xe2, 0x03, 0xff, 0x4a, 0xbb,
	0x5e, 0x71, 0x47, 0x32, 0x83, 0xc1, 0x7f, 0xb1, 0x47, 0x5f, 0xb2, 0xe7, 0xe9, 0x13, 0x76, 0x93,
	0xec, 0x51, 0x6e, 0xed, 0x8e, 0xf6, 0xd3, 0x68, 0x1e, 0xe7, 0x01, 0x11, 0x02, 0xdd, 0x92, 0xd9,
	0x1d, 0x4d, 0xbc, 0xdf, 0x9f, 0xc9, 0x27, 0x18, 0x73, 0x34, 0x85, 0x16, 0xa5, 0x75, 0xcd, 0x24,
	0x1d, 0x78, 0xf1, 0x92, 0xbc, 0x72, 0xad, 0x25, 0x1d, 0xde, 0xb8, 0xd6, 0xd2, 0xbd, 0xa3, 0x2a,
	0xf7, 0x8a, 0x71, 0xd4, 0xbf, 0x05, 0xa7, 0xe0, 0x9b, 0xb7, 0x29, 0x37, 0x99, 0xb1, 0xcc, 0x56,
	0x86, 0x8e, 0xd2, 0x68, 0xde, 0xcb, 0x03, 0x22, 0x13, 0xe8, 0x08, 0x4e, 0x5f, 0x7b, 0xae, 0x23,
	0x38, 0xf9, 0x00, 0x50, 0x68, 0x64, 0x16, 0x7f, 0x89, 0x03, 0xd2, 0xb1, 0x2f, 0xd4, 0x62, 0x9c,
	0x5e, 0x95, 0xbc, 0xd1, 0x27, 0xb5, 0x7e, 0x66, 0xdc, 0x7f, 0x59, 0xc1, 0xe9, 0x1b, 0x2f, 0xb8,
	0x63, 0x86, 0xf0, 0xee, 0x3b, 0xda, 0x1f, 0xcc, 0xa2, 0xb1, 0x21, 0xb1, 0x1c, 0x1f, 0x2b, 0x34,
	0xf6, 0x6e, 0x70, 0x6e, 0x58, 0x55, 0xe9, 0xa2, 0xc9, 0x2c, 0x20, 0xf7, 0xf5, 0x95, 0x41, 0x2d,
	0xdd, 0xd7, 0xd7, 0x59, 0x9d, 0x70, 0xc6, 0x81, 0xde, 0xb6, 0x31, 0xa5, 0x92, 0x06, 0xc9, 0x7b,
	0x18, 0xa2, 0xd6, 0x4a, 0xfb, 0x90, 0x23, 0xff, 0xd6, 0x33, 0x41, 0x3e, 0x43, 0x12, 0x12, 0xf7,
	0xed, 0x46, 0xab, 0xe9, 0x22, 0x6c, 0xd9, 0xa2, 0x29, 0xd4, 0x18, 0x56, 0x0f, 0x30, 0xc9, 0xeb,
	0xc5, 0x6c, 0x96, 0xef, 0x2f, 0x4c, 0xaf, 0xfb, 0x92, 0xf4, 0x54, 0xe0, 0xce, 0xcb, 0x67, 0x1f,
	0x5f, 0x70, 0xd4, 0x43, 0x67, 0xaf, 0x36, 0x7d, 0xbf, 0xf3, 0x5f, 0x9e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x33, 0x77, 0xaa, 0x17, 0x03, 0x00, 0x00,
}
