// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advertisement.proto

package com.lanlian.rpc.adver;

/**
 * Protobuf type {@code adv.AdvertisementReply}
 */
public final class AdvertisementReply extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:adv.AdvertisementReply)
		AdvertisementReplyOrBuilder {
	// Use AdvertisementReply.newBuilder() to construct.
	private AdvertisementReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private AdvertisementReply() {
		name_ = "";
		md5_ = "";
		startTime_ = 0L;
		endTime_ = 0L;
		source_ = "";
		fileUrl_ = "";
		state_ = 0;
		advertiser_ = "";
		errorCode_ = 0;
		signature_ = "";
		id_ = 0;
		advUrl_ = "";
		tid_ = 0L;
		fileName_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	@SuppressWarnings("unused")
	private AdvertisementReply(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();

					name_ = s;
					break;
				}
				case 18: {
					java.lang.String s = input.readStringRequireUtf8();

					md5_ = s;
					break;
				}
				case 24: {

					startTime_ = input.readInt64();
					break;
				}
				case 32: {

					endTime_ = input.readInt64();
					break;
				}
				case 42: {
					java.lang.String s = input.readStringRequireUtf8();

					source_ = s;
					break;
				}
				case 50: {
					java.lang.String s = input.readStringRequireUtf8();

					fileUrl_ = s;
					break;
				}
				case 56: {

					state_ = input.readInt32();
					break;
				}
				case 66: {
					java.lang.String s = input.readStringRequireUtf8();

					advertiser_ = s;
					break;
				}
				case 72: {

					errorCode_ = input.readInt32();
					break;
				}
				case 82: {
					java.lang.String s = input.readStringRequireUtf8();

					signature_ = s;
					break;
				}
				case 88: {

					id_ = input.readInt32();
					break;
				}
				case 98: {
					java.lang.String s = input.readStringRequireUtf8();

					advUrl_ = s;
					break;
				}
				case 104: {

					tid_ = input.readInt64();
					break;
				}
				case 114: {
					java.lang.String s = input.readStringRequireUtf8();

					fileName_ = s;
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.adver.AdverProto.internal_static_adv_AdvertisementReply_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.adver.AdverProto.internal_static_adv_AdvertisementReply_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.adver.AdvertisementReply.class,
						com.lanlian.rpc.adver.AdvertisementReply.Builder.class);
	}

	public static final int NAME_FIELD_NUMBER = 1;
	private volatile java.lang.Object name_;

	/**
	 * <code>optional string name = 1;</code>
	 */
	public java.lang.String getName() {
		java.lang.Object ref = name_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			name_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string name = 1;</code>
	 */
	public com.google.protobuf.ByteString getNameBytes() {
		java.lang.Object ref = name_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			name_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int MD5_FIELD_NUMBER = 2;
	private volatile java.lang.Object md5_;

	/**
	 * <code>optional string md5 = 2;</code>
	 */
	public java.lang.String getMd5() {
		java.lang.Object ref = md5_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			md5_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string md5 = 2;</code>
	 */
	public com.google.protobuf.ByteString getMd5Bytes() {
		java.lang.Object ref = md5_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			md5_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int STARTTIME_FIELD_NUMBER = 3;
	private long startTime_;

	/**
	 * <code>optional int64 startTime = 3;</code>
	 */
	public long getStartTime() {
		return startTime_;
	}

	public static final int ENDTIME_FIELD_NUMBER = 4;
	private long endTime_;

	/**
	 * <code>optional int64 endTime = 4;</code>
	 */
	public long getEndTime() {
		return endTime_;
	}

	public static final int SOURCE_FIELD_NUMBER = 5;
	private volatile java.lang.Object source_;

	/**
	 * <code>optional string source = 5;</code>
	 */
	public java.lang.String getSource() {
		java.lang.Object ref = source_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			source_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string source = 5;</code>
	 */
	public com.google.protobuf.ByteString getSourceBytes() {
		java.lang.Object ref = source_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			source_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int FILEURL_FIELD_NUMBER = 6;
	private volatile java.lang.Object fileUrl_;

	/**
	 * <code>optional string fileUrl = 6;</code>
	 */
	public java.lang.String getFileUrl() {
		java.lang.Object ref = fileUrl_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			fileUrl_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string fileUrl = 6;</code>
	 */
	public com.google.protobuf.ByteString getFileUrlBytes() {
		java.lang.Object ref = fileUrl_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			fileUrl_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int STATE_FIELD_NUMBER = 7;
	private int state_;

	/**
	 * <code>optional int32 state = 7;</code>
	 */
	public int getState() {
		return state_;
	}

	public static final int ADVERTISER_FIELD_NUMBER = 8;
	private volatile java.lang.Object advertiser_;

	/**
	 * <code>optional string advertiser = 8;</code>
	 */
	public java.lang.String getAdvertiser() {
		java.lang.Object ref = advertiser_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			advertiser_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string advertiser = 8;</code>
	 */
	public com.google.protobuf.ByteString getAdvertiserBytes() {
		java.lang.Object ref = advertiser_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			advertiser_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int ERRORCODE_FIELD_NUMBER = 9;
	private int errorCode_;

	/**
	 * <code>optional int32 errorCode = 9;</code>
	 */
	public int getErrorCode() {
		return errorCode_;
	}

	public static final int SIGNATURE_FIELD_NUMBER = 10;
	private volatile java.lang.Object signature_;

	/**
	 * <code>optional string signature = 10;</code>
	 */
	public java.lang.String getSignature() {
		java.lang.Object ref = signature_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			signature_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string signature = 10;</code>
	 */
	public com.google.protobuf.ByteString getSignatureBytes() {
		java.lang.Object ref = signature_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			signature_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int ID_FIELD_NUMBER = 11;
	private int id_;

	/**
	 * <code>optional int32 id = 11;</code>
	 */
	public int getId() {
		return id_;
	}

	public static final int ADVURL_FIELD_NUMBER = 12;
	private volatile java.lang.Object advUrl_;

	/**
	 * <code>optional string advUrl = 12;</code>
	 */
	public java.lang.String getAdvUrl() {
		java.lang.Object ref = advUrl_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			advUrl_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string advUrl = 12;</code>
	 */
	public com.google.protobuf.ByteString getAdvUrlBytes() {
		java.lang.Object ref = advUrl_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			advUrl_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int TID_FIELD_NUMBER = 13;
	private long tid_;

	/**
	 * <code>optional int64 tid = 13;</code>
	 */
	public long getTid() {
		return tid_;
	}

	public static final int FILENAME_FIELD_NUMBER = 14;
	private volatile java.lang.Object fileName_;

	/**
	 * <code>optional string fileName = 14;</code>
	 */
	public java.lang.String getFileName() {
		java.lang.Object ref = fileName_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			fileName_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string fileName = 14;</code>
	 */
	public com.google.protobuf.ByteString getFileNameBytes() {
		java.lang.Object ref = fileName_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			fileName_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!getNameBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
		}
		if (!getMd5Bytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 2, md5_);
		}
		if (startTime_ != 0L) {
			output.writeInt64(3, startTime_);
		}
		if (endTime_ != 0L) {
			output.writeInt64(4, endTime_);
		}
		if (!getSourceBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 5, source_);
		}
		if (!getFileUrlBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 6, fileUrl_);
		}
		if (state_ != 0) {
			output.writeInt32(7, state_);
		}
		if (!getAdvertiserBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 8, advertiser_);
		}
		if (errorCode_ != 0) {
			output.writeInt32(9, errorCode_);
		}
		if (!getSignatureBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 10, signature_);
		}
		if (id_ != 0) {
			output.writeInt32(11, id_);
		}
		if (!getAdvUrlBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 12, advUrl_);
		}
		if (tid_ != 0L) {
			output.writeInt64(13, tid_);
		}
		if (!getFileNameBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 14, fileName_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!getNameBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
		}
		if (!getMd5Bytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(2, md5_);
		}
		if (startTime_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, startTime_);
		}
		if (endTime_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, endTime_);
		}
		if (!getSourceBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(5, source_);
		}
		if (!getFileUrlBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(6, fileUrl_);
		}
		if (state_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(7, state_);
		}
		if (!getAdvertiserBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(8, advertiser_);
		}
		if (errorCode_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(9, errorCode_);
		}
		if (!getSignatureBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(10, signature_);
		}
		if (id_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(11, id_);
		}
		if (!getAdvUrlBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(12, advUrl_);
		}
		if (tid_ != 0L) {
			size += com.google.protobuf.CodedOutputStream.computeInt64Size(13, tid_);
		}
		if (!getFileNameBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(14, fileName_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.adver.AdvertisementReply parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.adver.AdvertisementReply prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code adv.AdvertisementReply}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:adv.AdvertisementReply)
			com.lanlian.rpc.adver.AdvertisementReplyOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.adver.AdverProto.internal_static_adv_AdvertisementReply_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.adver.AdverProto.internal_static_adv_AdvertisementReply_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.adver.AdvertisementReply.class,
							com.lanlian.rpc.adver.AdvertisementReply.Builder.class);
		}

		// Construct using com.lanlian.rpc.adver.AdvertisementReply.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			name_ = "";

			md5_ = "";

			startTime_ = 0L;

			endTime_ = 0L;

			source_ = "";

			fileUrl_ = "";

			state_ = 0;

			advertiser_ = "";

			errorCode_ = 0;

			signature_ = "";

			id_ = 0;

			advUrl_ = "";

			tid_ = 0L;

			fileName_ = "";

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.adver.AdverProto.internal_static_adv_AdvertisementReply_descriptor;
		}

		public com.lanlian.rpc.adver.AdvertisementReply getDefaultInstanceForType() {
			return com.lanlian.rpc.adver.AdvertisementReply.getDefaultInstance();
		}

		public com.lanlian.rpc.adver.AdvertisementReply build() {
			com.lanlian.rpc.adver.AdvertisementReply result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public com.lanlian.rpc.adver.AdvertisementReply buildPartial() {
			com.lanlian.rpc.adver.AdvertisementReply result = new com.lanlian.rpc.adver.AdvertisementReply(this);
			result.name_ = name_;
			result.md5_ = md5_;
			result.startTime_ = startTime_;
			result.endTime_ = endTime_;
			result.source_ = source_;
			result.fileUrl_ = fileUrl_;
			result.state_ = state_;
			result.advertiser_ = advertiser_;
			result.errorCode_ = errorCode_;
			result.signature_ = signature_;
			result.id_ = id_;
			result.advUrl_ = advUrl_;
			result.tid_ = tid_;
			result.fileName_ = fileName_;
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.adver.AdvertisementReply) {
				return mergeFrom((com.lanlian.rpc.adver.AdvertisementReply) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.adver.AdvertisementReply other) {
			if (other == com.lanlian.rpc.adver.AdvertisementReply.getDefaultInstance())
				return this;
			if (!other.getName().isEmpty()) {
				name_ = other.name_;
				onChanged();
			}
			if (!other.getMd5().isEmpty()) {
				md5_ = other.md5_;
				onChanged();
			}
			if (other.getStartTime() != 0L) {
				setStartTime(other.getStartTime());
			}
			if (other.getEndTime() != 0L) {
				setEndTime(other.getEndTime());
			}
			if (!other.getSource().isEmpty()) {
				source_ = other.source_;
				onChanged();
			}
			if (!other.getFileUrl().isEmpty()) {
				fileUrl_ = other.fileUrl_;
				onChanged();
			}
			if (other.getState() != 0) {
				setState(other.getState());
			}
			if (!other.getAdvertiser().isEmpty()) {
				advertiser_ = other.advertiser_;
				onChanged();
			}
			if (other.getErrorCode() != 0) {
				setErrorCode(other.getErrorCode());
			}
			if (!other.getSignature().isEmpty()) {
				signature_ = other.signature_;
				onChanged();
			}
			if (other.getId() != 0) {
				setId(other.getId());
			}
			if (!other.getAdvUrl().isEmpty()) {
				advUrl_ = other.advUrl_;
				onChanged();
			}
			if (other.getTid() != 0L) {
				setTid(other.getTid());
			}
			if (!other.getFileName().isEmpty()) {
				fileName_ = other.fileName_;
				onChanged();
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.adver.AdvertisementReply parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.adver.AdvertisementReply) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object name_ = "";

		/**
		 * <code>optional string name = 1;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		public Builder setName(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			name_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		public Builder clearName() {

			name_ = getDefaultInstance().getName();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string name = 1;</code>
		 */
		public Builder setNameBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			name_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object md5_ = "";

		/**
		 * <code>optional string md5 = 2;</code>
		 */
		public java.lang.String getMd5() {
			java.lang.Object ref = md5_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				md5_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string md5 = 2;</code>
		 */
		public com.google.protobuf.ByteString getMd5Bytes() {
			java.lang.Object ref = md5_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				md5_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string md5 = 2;</code>
		 */
		public Builder setMd5(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			md5_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string md5 = 2;</code>
		 */
		public Builder clearMd5() {

			md5_ = getDefaultInstance().getMd5();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string md5 = 2;</code>
		 */
		public Builder setMd5Bytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			md5_ = value;
			onChanged();
			return this;
		}

		private long startTime_;

		/**
		 * <code>optional int64 startTime = 3;</code>
		 */
		public long getStartTime() {
			return startTime_;
		}

		/**
		 * <code>optional int64 startTime = 3;</code>
		 */
		public Builder setStartTime(long value) {

			startTime_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int64 startTime = 3;</code>
		 */
		public Builder clearStartTime() {

			startTime_ = 0L;
			onChanged();
			return this;
		}

		private long endTime_;

		/**
		 * <code>optional int64 endTime = 4;</code>
		 */
		public long getEndTime() {
			return endTime_;
		}

		/**
		 * <code>optional int64 endTime = 4;</code>
		 */
		public Builder setEndTime(long value) {

			endTime_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int64 endTime = 4;</code>
		 */
		public Builder clearEndTime() {

			endTime_ = 0L;
			onChanged();
			return this;
		}

		private java.lang.Object source_ = "";

		/**
		 * <code>optional string source = 5;</code>
		 */
		public java.lang.String getSource() {
			java.lang.Object ref = source_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				source_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string source = 5;</code>
		 */
		public com.google.protobuf.ByteString getSourceBytes() {
			java.lang.Object ref = source_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				source_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string source = 5;</code>
		 */
		public Builder setSource(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			source_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string source = 5;</code>
		 */
		public Builder clearSource() {

			source_ = getDefaultInstance().getSource();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string source = 5;</code>
		 */
		public Builder setSourceBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			source_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object fileUrl_ = "";

		/**
		 * <code>optional string fileUrl = 6;</code>
		 */
		public java.lang.String getFileUrl() {
			java.lang.Object ref = fileUrl_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				fileUrl_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string fileUrl = 6;</code>
		 */
		public com.google.protobuf.ByteString getFileUrlBytes() {
			java.lang.Object ref = fileUrl_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				fileUrl_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string fileUrl = 6;</code>
		 */
		public Builder setFileUrl(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			fileUrl_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string fileUrl = 6;</code>
		 */
		public Builder clearFileUrl() {

			fileUrl_ = getDefaultInstance().getFileUrl();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string fileUrl = 6;</code>
		 */
		public Builder setFileUrlBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			fileUrl_ = value;
			onChanged();
			return this;
		}

		private int state_;

		/**
		 * <code>optional int32 state = 7;</code>
		 */
		public int getState() {
			return state_;
		}

		/**
		 * <code>optional int32 state = 7;</code>
		 */
		public Builder setState(int value) {

			state_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 state = 7;</code>
		 */
		public Builder clearState() {

			state_ = 0;
			onChanged();
			return this;
		}

		private java.lang.Object advertiser_ = "";

		/**
		 * <code>optional string advertiser = 8;</code>
		 */
		public java.lang.String getAdvertiser() {
			java.lang.Object ref = advertiser_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				advertiser_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string advertiser = 8;</code>
		 */
		public com.google.protobuf.ByteString getAdvertiserBytes() {
			java.lang.Object ref = advertiser_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				advertiser_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string advertiser = 8;</code>
		 */
		public Builder setAdvertiser(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			advertiser_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string advertiser = 8;</code>
		 */
		public Builder clearAdvertiser() {

			advertiser_ = getDefaultInstance().getAdvertiser();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string advertiser = 8;</code>
		 */
		public Builder setAdvertiserBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			advertiser_ = value;
			onChanged();
			return this;
		}

		private int errorCode_;

		/**
		 * <code>optional int32 errorCode = 9;</code>
		 */
		public int getErrorCode() {
			return errorCode_;
		}

		/**
		 * <code>optional int32 errorCode = 9;</code>
		 */
		public Builder setErrorCode(int value) {

			errorCode_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 errorCode = 9;</code>
		 */
		public Builder clearErrorCode() {

			errorCode_ = 0;
			onChanged();
			return this;
		}

		private java.lang.Object signature_ = "";

		/**
		 * <code>optional string signature = 10;</code>
		 */
		public java.lang.String getSignature() {
			java.lang.Object ref = signature_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				signature_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string signature = 10;</code>
		 */
		public com.google.protobuf.ByteString getSignatureBytes() {
			java.lang.Object ref = signature_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				signature_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string signature = 10;</code>
		 */
		public Builder setSignature(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			signature_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string signature = 10;</code>
		 */
		public Builder clearSignature() {

			signature_ = getDefaultInstance().getSignature();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string signature = 10;</code>
		 */
		public Builder setSignatureBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			signature_ = value;
			onChanged();
			return this;
		}

		private int id_;

		/**
		 * <code>optional int32 id = 11;</code>
		 */
		public int getId() {
			return id_;
		}

		/**
		 * <code>optional int32 id = 11;</code>
		 */
		public Builder setId(int value) {

			id_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 id = 11;</code>
		 */
		public Builder clearId() {

			id_ = 0;
			onChanged();
			return this;
		}

		private java.lang.Object advUrl_ = "";

		/**
		 * <code>optional string advUrl = 12;</code>
		 */
		public java.lang.String getAdvUrl() {
			java.lang.Object ref = advUrl_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				advUrl_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string advUrl = 12;</code>
		 */
		public com.google.protobuf.ByteString getAdvUrlBytes() {
			java.lang.Object ref = advUrl_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				advUrl_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string advUrl = 12;</code>
		 */
		public Builder setAdvUrl(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			advUrl_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string advUrl = 12;</code>
		 */
		public Builder clearAdvUrl() {

			advUrl_ = getDefaultInstance().getAdvUrl();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string advUrl = 12;</code>
		 */
		public Builder setAdvUrlBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			advUrl_ = value;
			onChanged();
			return this;
		}

		private long tid_;

		/**
		 * <code>optional int64 tid = 13;</code>
		 */
		public long getTid() {
			return tid_;
		}

		/**
		 * <code>optional int64 tid = 13;</code>
		 */
		public Builder setTid(long value) {

			tid_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int64 tid = 13;</code>
		 */
		public Builder clearTid() {

			tid_ = 0L;
			onChanged();
			return this;
		}

		private java.lang.Object fileName_ = "";

		/**
		 * <code>optional string fileName = 14;</code>
		 */
		public java.lang.String getFileName() {
			java.lang.Object ref = fileName_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				fileName_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string fileName = 14;</code>
		 */
		public com.google.protobuf.ByteString getFileNameBytes() {
			java.lang.Object ref = fileName_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				fileName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string fileName = 14;</code>
		 */
		public Builder setFileName(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			fileName_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string fileName = 14;</code>
		 */
		public Builder clearFileName() {

			fileName_ = getDefaultInstance().getFileName();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string fileName = 14;</code>
		 */
		public Builder setFileNameBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			fileName_ = value;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:adv.AdvertisementReply)
	}

	// @@protoc_insertion_point(class_scope:adv.AdvertisementReply)
	private static final com.lanlian.rpc.adver.AdvertisementReply DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.adver.AdvertisementReply();
	}

	public static com.lanlian.rpc.adver.AdvertisementReply getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<AdvertisementReply> PARSER = new com.google.protobuf.AbstractParser<AdvertisementReply>() {
		public AdvertisementReply parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new AdvertisementReply(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<AdvertisementReply> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<AdvertisementReply> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.adver.AdvertisementReply getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
