// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advertisement.proto

package com.lanlian.rpc.adver;

public interface AdvertisementReplyOrBuilder extends
		// @@protoc_insertion_point(interface_extends:adv.AdvertisementReply)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>optional string name = 1;</code>
	 */
	java.lang.String getName();

	/**
	 * <code>optional string name = 1;</code>
	 */
	com.google.protobuf.ByteString getNameBytes();

	/**
	 * <code>optional string md5 = 2;</code>
	 */
	java.lang.String getMd5();

	/**
	 * <code>optional string md5 = 2;</code>
	 */
	com.google.protobuf.ByteString getMd5Bytes();

	/**
	 * <code>optional int64 startTime = 3;</code>
	 */
	long getStartTime();

	/**
	 * <code>optional int64 endTime = 4;</code>
	 */
	long getEndTime();

	/**
	 * <code>optional string source = 5;</code>
	 */
	java.lang.String getSource();

	/**
	 * <code>optional string source = 5;</code>
	 */
	com.google.protobuf.ByteString getSourceBytes();

	/**
	 * <code>optional string fileUrl = 6;</code>
	 */
	java.lang.String getFileUrl();

	/**
	 * <code>optional string fileUrl = 6;</code>
	 */
	com.google.protobuf.ByteString getFileUrlBytes();

	/**
	 * <code>optional int32 state = 7;</code>
	 */
	int getState();

	/**
	 * <code>optional string advertiser = 8;</code>
	 */
	java.lang.String getAdvertiser();

	/**
	 * <code>optional string advertiser = 8;</code>
	 */
	com.google.protobuf.ByteString getAdvertiserBytes();

	/**
	 * <code>optional int32 errorCode = 9;</code>
	 */
	int getErrorCode();

	/**
	 * <code>optional string signature = 10;</code>
	 */
	java.lang.String getSignature();

	/**
	 * <code>optional string signature = 10;</code>
	 */
	com.google.protobuf.ByteString getSignatureBytes();

	/**
	 * <code>optional int32 id = 11;</code>
	 */
	int getId();

	/**
	 * <code>optional string advUrl = 12;</code>
	 */
	java.lang.String getAdvUrl();

	/**
	 * <code>optional string advUrl = 12;</code>
	 */
	com.google.protobuf.ByteString getAdvUrlBytes();

	/**
	 * <code>optional int64 tid = 13;</code>
	 */
	long getTid();

	/**
	 * <code>optional string fileName = 14;</code>
	 */
	java.lang.String getFileName();

	/**
	 * <code>optional string fileName = 14;</code>
	 */
	com.google.protobuf.ByteString getFileNameBytes();
}
