[auth]
host="0.0.0.0"
port="7010"
[mysql]
database="auth"
user="root"
password="Radacat2017"
host="192.168.1.6"
port="3306"
automigrate=false
[redis]
url= "redis://root:radacat1234@192.168.1.6:6379/0"


