// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

/**
 * Protobuf type {@code setting.GetAllVersionsResponse}
 */
public final class GetAllVersionsResponse extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:setting.GetAllVersionsResponse)
		GetAllVersionsResponseOrBuilder {
	// Use GetAllVersionsResponse.newBuilder() to construct.
	private GetAllVersionsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private GetAllVersionsResponse() {
		errorCode_ = 0;
		versions_ = java.util.Collections.emptyList();
		totalCount_ = 0;
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	private GetAllVersionsResponse(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 8: {

					errorCode_ = input.readInt32();
					break;
				}
				case 18: {
					if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
						versions_ = new java.util.ArrayList<com.lanlian.rpc.version.Version>();
						mutable_bitField0_ |= 0x00000002;
					}
					versions_.add(input.readMessage(com.lanlian.rpc.version.Version.parser(), extensionRegistry));
					break;
				}
				case 24: {

					totalCount_ = input.readInt32();
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
				versions_ = java.util.Collections.unmodifiableList(versions_);
			}
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsResponse_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetAllVersionsResponse.class,
						com.lanlian.rpc.version.GetAllVersionsResponse.Builder.class);
	}

	@SuppressWarnings("unused")
	private int bitField0_;
	public static final int ERRORCODE_FIELD_NUMBER = 1;
	private int errorCode_;

	/**
	 * <code>optional int32 ErrorCode = 1;</code>
	 */
	public int getErrorCode() {
		return errorCode_;
	}

	public static final int VERSIONS_FIELD_NUMBER = 2;
	private java.util.List<com.lanlian.rpc.version.Version> versions_;

	/**
	 * <code>repeated .setting.Version versions = 2;</code>
	 */
	public java.util.List<com.lanlian.rpc.version.Version> getVersionsList() {
		return versions_;
	}

	/**
	 * <code>repeated .setting.Version versions = 2;</code>
	 */
	public java.util.List<? extends com.lanlian.rpc.version.VersionOrBuilder> getVersionsOrBuilderList() {
		return versions_;
	}

	/**
	 * <code>repeated .setting.Version versions = 2;</code>
	 */
	public int getVersionsCount() {
		return versions_.size();
	}

	/**
	 * <code>repeated .setting.Version versions = 2;</code>
	 */
	public com.lanlian.rpc.version.Version getVersions(int index) {
		return versions_.get(index);
	}

	/**
	 * <code>repeated .setting.Version versions = 2;</code>
	 */
	public com.lanlian.rpc.version.VersionOrBuilder getVersionsOrBuilder(int index) {
		return versions_.get(index);
	}

	public static final int TOTALCOUNT_FIELD_NUMBER = 3;
	private int totalCount_;

	/**
	 * <code>optional int32 totalCount = 3;</code>
	 */
	public int getTotalCount() {
		return totalCount_;
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (errorCode_ != 0) {
			output.writeInt32(1, errorCode_);
		}
		for (int i = 0; i < versions_.size(); i++) {
			output.writeMessage(2, versions_.get(i));
		}
		if (totalCount_ != 0) {
			output.writeInt32(3, totalCount_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (errorCode_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, errorCode_);
		}
		for (int i = 0; i < versions_.size(); i++) {
			size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, versions_.get(i));
		}
		if (totalCount_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, totalCount_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.version.GetAllVersionsResponse prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code setting.GetAllVersionsResponse}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:setting.GetAllVersionsResponse)
			com.lanlian.rpc.version.GetAllVersionsResponseOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetAllVersionsResponse.class,
							com.lanlian.rpc.version.GetAllVersionsResponse.Builder.class);
		}

		// Construct using com.lanlian.rpc.version.GetAllVersionsResponse.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				getVersionsFieldBuilder();
			}
		}

		public Builder clear() {
			super.clear();
			errorCode_ = 0;

			if (versionsBuilder_ == null) {
				versions_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
			} else {
				versionsBuilder_.clear();
			}
			totalCount_ = 0;

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetAllVersionsResponse_descriptor;
		}

		public com.lanlian.rpc.version.GetAllVersionsResponse getDefaultInstanceForType() {
			return com.lanlian.rpc.version.GetAllVersionsResponse.getDefaultInstance();
		}

		public com.lanlian.rpc.version.GetAllVersionsResponse build() {
			com.lanlian.rpc.version.GetAllVersionsResponse result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@SuppressWarnings("unused")
		public com.lanlian.rpc.version.GetAllVersionsResponse buildPartial() {
			com.lanlian.rpc.version.GetAllVersionsResponse result = new com.lanlian.rpc.version.GetAllVersionsResponse(
					this);
			int from_bitField0_ = bitField0_;
			int to_bitField0_ = 0;
			result.errorCode_ = errorCode_;
			if (versionsBuilder_ == null) {
				if (((bitField0_ & 0x00000002) == 0x00000002)) {
					versions_ = java.util.Collections.unmodifiableList(versions_);
					bitField0_ = (bitField0_ & ~0x00000002);
				}
				result.versions_ = versions_;
			} else {
				result.versions_ = versionsBuilder_.build();
			}
			result.totalCount_ = totalCount_;
			result.bitField0_ = to_bitField0_;
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.version.GetAllVersionsResponse) {
				return mergeFrom((com.lanlian.rpc.version.GetAllVersionsResponse) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.version.GetAllVersionsResponse other) {
			if (other == com.lanlian.rpc.version.GetAllVersionsResponse.getDefaultInstance())
				return this;
			if (other.getErrorCode() != 0) {
				setErrorCode(other.getErrorCode());
			}
			if (versionsBuilder_ == null) {
				if (!other.versions_.isEmpty()) {
					if (versions_.isEmpty()) {
						versions_ = other.versions_;
						bitField0_ = (bitField0_ & ~0x00000002);
					} else {
						ensureVersionsIsMutable();
						versions_.addAll(other.versions_);
					}
					onChanged();
				}
			} else {
				if (!other.versions_.isEmpty()) {
					if (versionsBuilder_.isEmpty()) {
						versionsBuilder_.dispose();
						versionsBuilder_ = null;
						versions_ = other.versions_;
						bitField0_ = (bitField0_ & ~0x00000002);
						versionsBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
								? getVersionsFieldBuilder()
								: null;
					} else {
						versionsBuilder_.addAllMessages(other.versions_);
					}
				}
			}
			if (other.getTotalCount() != 0) {
				setTotalCount(other.getTotalCount());
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.version.GetAllVersionsResponse parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.version.GetAllVersionsResponse) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int bitField0_;

		private int errorCode_;

		/**
		 * <code>optional int32 ErrorCode = 1;</code>
		 */
		public int getErrorCode() {
			return errorCode_;
		}

		/**
		 * <code>optional int32 ErrorCode = 1;</code>
		 */
		public Builder setErrorCode(int value) {

			errorCode_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 ErrorCode = 1;</code>
		 */
		public Builder clearErrorCode() {

			errorCode_ = 0;
			onChanged();
			return this;
		}

		private java.util.List<com.lanlian.rpc.version.Version> versions_ = java.util.Collections.emptyList();

		private void ensureVersionsIsMutable() {
			if (!((bitField0_ & 0x00000002) == 0x00000002)) {
				versions_ = new java.util.ArrayList<com.lanlian.rpc.version.Version>(versions_);
				bitField0_ |= 0x00000002;
			}
		}

		private com.google.protobuf.RepeatedFieldBuilder<com.lanlian.rpc.version.Version, com.lanlian.rpc.version.Version.Builder, com.lanlian.rpc.version.VersionOrBuilder> versionsBuilder_;

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public java.util.List<com.lanlian.rpc.version.Version> getVersionsList() {
			if (versionsBuilder_ == null) {
				return java.util.Collections.unmodifiableList(versions_);
			} else {
				return versionsBuilder_.getMessageList();
			}
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public int getVersionsCount() {
			if (versionsBuilder_ == null) {
				return versions_.size();
			} else {
				return versionsBuilder_.getCount();
			}
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public com.lanlian.rpc.version.Version getVersions(int index) {
			if (versionsBuilder_ == null) {
				return versions_.get(index);
			} else {
				return versionsBuilder_.getMessage(index);
			}
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder setVersions(int index, com.lanlian.rpc.version.Version value) {
			if (versionsBuilder_ == null) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionsIsMutable();
				versions_.set(index, value);
				onChanged();
			} else {
				versionsBuilder_.setMessage(index, value);
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder setVersions(int index, com.lanlian.rpc.version.Version.Builder builderForValue) {
			if (versionsBuilder_ == null) {
				ensureVersionsIsMutable();
				versions_.set(index, builderForValue.build());
				onChanged();
			} else {
				versionsBuilder_.setMessage(index, builderForValue.build());
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder addVersions(com.lanlian.rpc.version.Version value) {
			if (versionsBuilder_ == null) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionsIsMutable();
				versions_.add(value);
				onChanged();
			} else {
				versionsBuilder_.addMessage(value);
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder addVersions(int index, com.lanlian.rpc.version.Version value) {
			if (versionsBuilder_ == null) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureVersionsIsMutable();
				versions_.add(index, value);
				onChanged();
			} else {
				versionsBuilder_.addMessage(index, value);
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder addVersions(com.lanlian.rpc.version.Version.Builder builderForValue) {
			if (versionsBuilder_ == null) {
				ensureVersionsIsMutable();
				versions_.add(builderForValue.build());
				onChanged();
			} else {
				versionsBuilder_.addMessage(builderForValue.build());
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder addVersions(int index, com.lanlian.rpc.version.Version.Builder builderForValue) {
			if (versionsBuilder_ == null) {
				ensureVersionsIsMutable();
				versions_.add(index, builderForValue.build());
				onChanged();
			} else {
				versionsBuilder_.addMessage(index, builderForValue.build());
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder addAllVersions(java.lang.Iterable<? extends com.lanlian.rpc.version.Version> values) {
			if (versionsBuilder_ == null) {
				ensureVersionsIsMutable();
				com.google.protobuf.AbstractMessageLite.Builder.addAll(values, versions_);
				onChanged();
			} else {
				versionsBuilder_.addAllMessages(values);
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder clearVersions() {
			if (versionsBuilder_ == null) {
				versions_ = java.util.Collections.emptyList();
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
			} else {
				versionsBuilder_.clear();
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public Builder removeVersions(int index) {
			if (versionsBuilder_ == null) {
				ensureVersionsIsMutable();
				versions_.remove(index);
				onChanged();
			} else {
				versionsBuilder_.remove(index);
			}
			return this;
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public com.lanlian.rpc.version.Version.Builder getVersionsBuilder(int index) {
			return getVersionsFieldBuilder().getBuilder(index);
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public com.lanlian.rpc.version.VersionOrBuilder getVersionsOrBuilder(int index) {
			if (versionsBuilder_ == null) {
				return versions_.get(index);
			} else {
				return versionsBuilder_.getMessageOrBuilder(index);
			}
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public java.util.List<? extends com.lanlian.rpc.version.VersionOrBuilder> getVersionsOrBuilderList() {
			if (versionsBuilder_ != null) {
				return versionsBuilder_.getMessageOrBuilderList();
			} else {
				return java.util.Collections.unmodifiableList(versions_);
			}
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public com.lanlian.rpc.version.Version.Builder addVersionsBuilder() {
			return getVersionsFieldBuilder().addBuilder(com.lanlian.rpc.version.Version.getDefaultInstance());
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public com.lanlian.rpc.version.Version.Builder addVersionsBuilder(int index) {
			return getVersionsFieldBuilder().addBuilder(index, com.lanlian.rpc.version.Version.getDefaultInstance());
		}

		/**
		 * <code>repeated .setting.Version versions = 2;</code>
		 */
		public java.util.List<com.lanlian.rpc.version.Version.Builder> getVersionsBuilderList() {
			return getVersionsFieldBuilder().getBuilderList();
		}

		private com.google.protobuf.RepeatedFieldBuilder<com.lanlian.rpc.version.Version, com.lanlian.rpc.version.Version.Builder, com.lanlian.rpc.version.VersionOrBuilder> getVersionsFieldBuilder() {
			if (versionsBuilder_ == null) {
				versionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<com.lanlian.rpc.version.Version, com.lanlian.rpc.version.Version.Builder, com.lanlian.rpc.version.VersionOrBuilder>(
						versions_, ((bitField0_ & 0x00000002) == 0x00000002), getParentForChildren(), isClean());
				versions_ = null;
			}
			return versionsBuilder_;
		}

		private int totalCount_;

		/**
		 * <code>optional int32 totalCount = 3;</code>
		 */
		public int getTotalCount() {
			return totalCount_;
		}

		/**
		 * <code>optional int32 totalCount = 3;</code>
		 */
		public Builder setTotalCount(int value) {

			totalCount_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional int32 totalCount = 3;</code>
		 */
		public Builder clearTotalCount() {

			totalCount_ = 0;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:setting.GetAllVersionsResponse)
	}

	// @@protoc_insertion_point(class_scope:setting.GetAllVersionsResponse)
	private static final com.lanlian.rpc.version.GetAllVersionsResponse DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.version.GetAllVersionsResponse();
	}

	public static com.lanlian.rpc.version.GetAllVersionsResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<GetAllVersionsResponse> PARSER = new com.google.protobuf.AbstractParser<GetAllVersionsResponse>() {
		public GetAllVersionsResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new GetAllVersionsResponse(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<GetAllVersionsResponse> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<GetAllVersionsResponse> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.version.GetAllVersionsResponse getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
