// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

/**
 * Protobuf type {@code setting.GetLatestVersionRequest}
 */
public final class GetLatestVersionRequest extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:setting.GetLatestVersionRequest)
		GetLatestVersionRequestOrBuilder {
	// Use GetLatestVersionRequest.newBuilder() to construct.
	private GetLatestVersionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private GetLatestVersionRequest() {
		device_ = "";
		source_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	@SuppressWarnings("unused")
	private GetLatestVersionRequest(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		int mutable_bitField0_ = 0;
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();

					device_ = s;
					break;
				}
				case 18: {
					java.lang.String s = input.readStringRequireUtf8();

					source_ = s;
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetLatestVersionRequest_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetLatestVersionRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetLatestVersionRequest.class,
						com.lanlian.rpc.version.GetLatestVersionRequest.Builder.class);
	}

	public static final int DEVICE_FIELD_NUMBER = 1;
	private volatile java.lang.Object device_;

	/**
	 * <code>optional string device = 1;</code>
	 */
	public java.lang.String getDevice() {
		java.lang.Object ref = device_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			device_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string device = 1;</code>
	 */
	public com.google.protobuf.ByteString getDeviceBytes() {
		java.lang.Object ref = device_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			device_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int SOURCE_FIELD_NUMBER = 2;
	private volatile java.lang.Object source_;

	/**
	 * <code>optional string source = 2;</code>
	 */
	public java.lang.String getSource() {
		java.lang.Object ref = source_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			source_ = s;
			return s;
		}
	}

	/**
	 * <code>optional string source = 2;</code>
	 */
	public com.google.protobuf.ByteString getSourceBytes() {
		java.lang.Object ref = source_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			source_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!getDeviceBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 1, device_);
		}
		if (!getSourceBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessage.writeString(output, 2, source_);
		}
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!getDeviceBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(1, device_);
		}
		if (!getSourceBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessage.computeStringSize(2, source_);
		}
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.version.GetLatestVersionRequest prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code setting.GetLatestVersionRequest}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:setting.GetLatestVersionRequest)
			com.lanlian.rpc.version.GetLatestVersionRequestOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetLatestVersionRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetLatestVersionRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.version.GetLatestVersionRequest.class,
							com.lanlian.rpc.version.GetLatestVersionRequest.Builder.class);
		}

		// Construct using com.lanlian.rpc.version.GetLatestVersionRequest.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			device_ = "";

			source_ = "";

			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.version.VersionProto.internal_static_setting_GetLatestVersionRequest_descriptor;
		}

		public com.lanlian.rpc.version.GetLatestVersionRequest getDefaultInstanceForType() {
			return com.lanlian.rpc.version.GetLatestVersionRequest.getDefaultInstance();
		}

		public com.lanlian.rpc.version.GetLatestVersionRequest build() {
			com.lanlian.rpc.version.GetLatestVersionRequest result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public com.lanlian.rpc.version.GetLatestVersionRequest buildPartial() {
			com.lanlian.rpc.version.GetLatestVersionRequest result = new com.lanlian.rpc.version.GetLatestVersionRequest(
					this);
			result.device_ = device_;
			result.source_ = source_;
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.version.GetLatestVersionRequest) {
				return mergeFrom((com.lanlian.rpc.version.GetLatestVersionRequest) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.version.GetLatestVersionRequest other) {
			if (other == com.lanlian.rpc.version.GetLatestVersionRequest.getDefaultInstance())
				return this;
			if (!other.getDevice().isEmpty()) {
				device_ = other.device_;
				onChanged();
			}
			if (!other.getSource().isEmpty()) {
				source_ = other.source_;
				onChanged();
			}
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.version.GetLatestVersionRequest parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.version.GetLatestVersionRequest) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object device_ = "";

		/**
		 * <code>optional string device = 1;</code>
		 */
		public java.lang.String getDevice() {
			java.lang.Object ref = device_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				device_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string device = 1;</code>
		 */
		public com.google.protobuf.ByteString getDeviceBytes() {
			java.lang.Object ref = device_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				device_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string device = 1;</code>
		 */
		public Builder setDevice(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			device_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string device = 1;</code>
		 */
		public Builder clearDevice() {

			device_ = getDefaultInstance().getDevice();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string device = 1;</code>
		 */
		public Builder setDeviceBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			device_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object source_ = "";

		/**
		 * <code>optional string source = 2;</code>
		 */
		public java.lang.String getSource() {
			java.lang.Object ref = source_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				source_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>optional string source = 2;</code>
		 */
		public com.google.protobuf.ByteString getSourceBytes() {
			java.lang.Object ref = source_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				source_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>optional string source = 2;</code>
		 */
		public Builder setSource(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			source_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>optional string source = 2;</code>
		 */
		public Builder clearSource() {

			source_ = getDefaultInstance().getSource();
			onChanged();
			return this;
		}

		/**
		 * <code>optional string source = 2;</code>
		 */
		public Builder setSourceBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			source_ = value;
			onChanged();
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:setting.GetLatestVersionRequest)
	}

	// @@protoc_insertion_point(class_scope:setting.GetLatestVersionRequest)
	private static final com.lanlian.rpc.version.GetLatestVersionRequest DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.version.GetLatestVersionRequest();
	}

	public static com.lanlian.rpc.version.GetLatestVersionRequest getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<GetLatestVersionRequest> PARSER = new com.google.protobuf.AbstractParser<GetLatestVersionRequest>() {
		public GetLatestVersionRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new GetLatestVersionRequest(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<GetLatestVersionRequest> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<GetLatestVersionRequest> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.version.GetLatestVersionRequest getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
