// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radacat_version.proto

package com.lanlian.rpc.version;

public interface UpdateVersionResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:setting.UpdateVersionResponse)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>optional int32 ErrorCode = 1;</code>
	 */
	int getErrorCode();
}
