// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: twins-agent.proto

package com.lanlian.rpc.twins;

/**
 * Protobuf type {@code agent.AddTwinsAgentResponse}
 */
public final class AddTwinsAgentResponse extends com.google.protobuf.GeneratedMessage implements
		// @@protoc_insertion_point(message_implements:agent.AddTwinsAgentResponse)
		AddTwinsAgentResponseOrBuilder {
	// Use AddTwinsAgentResponse.newBuilder() to construct.
	private AddTwinsAgentResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
		super(builder);
	}

	private AddTwinsAgentResponse() {
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
	}

	private AddTwinsAgentResponse(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
		this();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				default: {
					if (!input.skipField(tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw new RuntimeException(e.setUnfinishedMessage(this));
		} catch (java.io.IOException e) {
			throw new RuntimeException(
					new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this));
		} finally {
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.lanlian.rpc.twins.TwinsAgentServerProto.internal_static_agent_AddTwinsAgentResponse_descriptor;
	}

	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.lanlian.rpc.twins.TwinsAgentServerProto.internal_static_agent_AddTwinsAgentResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.lanlian.rpc.twins.AddTwinsAgentResponse.class,
						com.lanlian.rpc.twins.AddTwinsAgentResponse.Builder.class);
	}

	private byte memoizedIsInitialized = -1;

	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
	}

	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		memoizedSize = size;
		return size;
	}

	private static final long serialVersionUID = 0L;

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseDelimitedFrom(input, extensionRegistry);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return PARSER.parseFrom(input);
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return PARSER.parseFrom(input, extensionRegistry);
	}

	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.lanlian.rpc.twins.AddTwinsAgentResponse prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code agent.AddTwinsAgentResponse}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:agent.AddTwinsAgentResponse)
			com.lanlian.rpc.twins.AddTwinsAgentResponseOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.lanlian.rpc.twins.TwinsAgentServerProto.internal_static_agent_AddTwinsAgentResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.lanlian.rpc.twins.TwinsAgentServerProto.internal_static_agent_AddTwinsAgentResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.lanlian.rpc.twins.AddTwinsAgentResponse.class,
							com.lanlian.rpc.twins.AddTwinsAgentResponse.Builder.class);
		}

		// Construct using com.lanlian.rpc.twins.AddTwinsAgentResponse.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
			}
		}

		public Builder clear() {
			super.clear();
			return this;
		}

		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.lanlian.rpc.twins.TwinsAgentServerProto.internal_static_agent_AddTwinsAgentResponse_descriptor;
		}

		public com.lanlian.rpc.twins.AddTwinsAgentResponse getDefaultInstanceForType() {
			return com.lanlian.rpc.twins.AddTwinsAgentResponse.getDefaultInstance();
		}

		public com.lanlian.rpc.twins.AddTwinsAgentResponse build() {
			com.lanlian.rpc.twins.AddTwinsAgentResponse result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		public com.lanlian.rpc.twins.AddTwinsAgentResponse buildPartial() {
			com.lanlian.rpc.twins.AddTwinsAgentResponse result = new com.lanlian.rpc.twins.AddTwinsAgentResponse(this);
			onBuilt();
			return result;
		}

		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.lanlian.rpc.twins.AddTwinsAgentResponse) {
				return mergeFrom((com.lanlian.rpc.twins.AddTwinsAgentResponse) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.lanlian.rpc.twins.AddTwinsAgentResponse other) {
			if (other == com.lanlian.rpc.twins.AddTwinsAgentResponse.getDefaultInstance())
				return this;
			onChanged();
			return this;
		}

		public final boolean isInitialized() {
			return true;
		}

		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.lanlian.rpc.twins.AddTwinsAgentResponse parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.lanlian.rpc.twins.AddTwinsAgentResponse) e.getUnfinishedMessage();
				throw e;
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return this;
		}

		// @@protoc_insertion_point(builder_scope:agent.AddTwinsAgentResponse)
	}

	// @@protoc_insertion_point(class_scope:agent.AddTwinsAgentResponse)
	private static final com.lanlian.rpc.twins.AddTwinsAgentResponse DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.lanlian.rpc.twins.AddTwinsAgentResponse();
	}

	public static com.lanlian.rpc.twins.AddTwinsAgentResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<AddTwinsAgentResponse> PARSER = new com.google.protobuf.AbstractParser<AddTwinsAgentResponse>() {
		public AddTwinsAgentResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			try {
				return new AddTwinsAgentResponse(input, extensionRegistry);
			} catch (RuntimeException e) {
				if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
					throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
				}
				throw e;
			}
		}
	};

	public static com.google.protobuf.Parser<AddTwinsAgentResponse> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<AddTwinsAgentResponse> getParserForType() {
		return PARSER;
	}

	public com.lanlian.rpc.twins.AddTwinsAgentResponse getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
