#[auth]
#host="0.0.0.0"
#port="7010"
#[mysql]
#database="auth"
#user="auth"
#password="Auth!123."
#host="39.105.57.122"
#port="3306"
#automigrate=false
#[redis]
#url= "redis://root:radacat1234@39.105.57.122:6379/0"

[auth]
host="0.0.0.0"
port="7010"
[mysql]
database="auth"
user="root"
password="Radacat2017"
host="127.0.0.1"
port="3306"
automigrate=false
[redis]
url= "redis://root:radacat1234@127.0.0.1:6379/0"