account-domain-http:
  host: 0.0.0.0
  port: 7003

redis:
  - name: persistence
    password: radacat1234
    host: rm6379.redis.radacat.com
    port: 6379
    maxIdle: 20
    maxActive: 5
  - name: nopersistence
    password: radacat1234
    host: rm6380.redis.radacat.com
    port: 6380
    maxIdle: 20
    maxActive: 5

metrics:
  host: 192.168.0.121
  port: 9090
  interval: 5
  enable: true #1:enable; 0:disable

etcd:
  name: uid_generator
  host: 192.168.0.121
  port: 2379
  enable: false  #1:enable; 0:disable
